propelorm/Propel2

- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
If I want to check if something exists currently I would do something like this:
```php
CmsCompanyQuery::create()->count() > 1;
```
Executes
````sql
SELECT COUNT(*) FROM cms_company;
````
But `count()` is expensive on larger tables, so I'd need to keep in mind to limit it:
````php
CmsCompanyQuery::create()->limit(1)->count() > 1;
````
Which surprisingly produces
```sql
SELECT COUNT(*) FROM (SELECT cms_company.com_id, cms_company.media_id, cms_company.admin_id, cms_company.com_name, cms_company.com_email, cms_company.com_address, cms_company.com_address2, cms_company.com_postal, cms_company.com_country, cms_company.com_employee, cms_company.com_skin, cms_company.com_theme, cms_company.com_activity, cms_company.com_status, cms_company.com_created, cms_company.com_modified, …
```
> Add an API for exists().

- src/Propel/Common/Config/PropelConfiguration.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- src/Propel/Runtime/Exception/EntityNotFoundException.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
Implementation of #803 
This adds `requireOne()`, `requireOneBy($column, $value)` and `requireOneByArray($values)` to `ModelCriteria`. The `ModelCriteria` also provides magic methods for `requireOneByXXX` and `requireOneByXXXAndXXX`. The generated query classes have `@method`-annotations for these magic methods to support autocompletion. 
---
You can now do something like:
```php
<?php
// ...
try {
echo 'Hello ' . UserQuery::create()->requireOneById($_GET['id'])->getName();
} catch (\Propel\Runtime\Exception\ModelNotFoundException $e) {
echo $e->getMessage();
}
```
Which will output 'Hello Marc' or 'User could not be found'  depending on whenever the given user-id exists.
---
You can customize the exception class in the propel config:
```yaml
propel
generator:
objectModel: …
```
> require-api: requireOne, requireOneByXXX, requireByArray

- src/Propel/Generator/Manager/AbstractManager.php
This improves the error message when you include an external schema which could not be found by propel. Currently you get the following error:
```
Warning: DOMDocument::load(): Empty string supplied as input
```
Now you get
```
Unable to find external schema 'my-external-schema.xml'
```
Propel applies `realpath` to the path given by the user. If `realpath` cannot resolve the given path it'll return `false`. Now `false` is given to `DOMDocument::load`, which logs a php warning because of invalid input.
> Improved error message when external schema cannot be found

- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
Thanks for the require* methods! :+1: 
I would like to have a `requirePk` method (like `findPk`). Is there a reason why this method was not added?
> Add method requirePk() to Query classes

- src/Propel/Generator/Behavior/AggregateColumn/AggregateColumnBehavior.php
- src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- src/Propel/Generator/Manager/GraphvizManager.php
- src/Propel/Generator/Model/Diff/TableComparator.php
- src/Propel/Generator/Model/ForeignKey.php
- src/Propel/Generator/Model/Table.php
- src/Propel/Generator/Platform/DefaultPlatform.php
- src/Propel/Generator/Platform/MssqlPlatform.php
- src/Propel/Generator/Platform/MysqlPlatform.php
- src/Propel/Generator/Platform/OraclePlatform.php
- src/Propel/Generator/Platform/SqlitePlatform.php
- src/Propel/Runtime/ActiveQuery/Join.php
- src/Propel/Runtime/ActiveQuery/ModelJoin.php
- src/Propel/Runtime/Map/RelationMap.php
- src/Propel/Runtime/Map/TableMap.php
- tests/Fixtures/bookstore/schema.xml
- tests/Propel/Tests/BookstoreLoggingTest.php
- tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
- tests/Propel/Tests/Generator/Model/ForeignKeyTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/JoinTest.php
> Added support for polymorphic relations. Fixes #487.

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
On columns without explicit type hinting, like PropelType::Object, no param type was set:
```php
/**
* Set the value of [sms_per_day] column.
*
* @param $v new value
* @return \Valid\NameSpace\Model The current object (for fluent API support)
*/
```
Leading to wrong IDE assumption for param type equals `Base\new`. By adding this fix doc block generation results in:
```php
/**
* Set the value of [sms_per_day] column.
*
* @param $v mixed new value
* @return \Valid\NameSpace\Model The current object (for fluent API support)
*/
```
> fix typehining on generated doc blocks by adding default 'mixed'' value

- src/Propel/Runtime/Collection/OnDemandCollection.php
- src/Propel/Runtime/Formatter/AbstractFormatter.php
Thus we don't fill our local instance collection inside the OnDemandFormatter we don't get into filling memory issues over time.
> Fix performance issues on OnDemandFormatter as in ObjectFormatter

- src/Propel/Generator/Platform/MysqlPlatform.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
- Copied code from Propel 1
- Changed methods, so the statements can get merged
> Migration: Missing "AFTER"/"FIRST" when adding columns (MySQL)

- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
Please merge if it’s the desired behaviour. There is no other way of reseting the `select` field, since the `select()` method doesn’t allow `null`.
> `ModelCriteria::clear()` resets the `$select` value

- src/Propel/Generator/Platform/PgsqlPlatform.php
According to http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
> The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.
> Fix PgsqlPlatform::getMaxColumnNameLength()

- src/Propel/Generator/Command/InitCommand.php
Hello,
This pull request fixes PostgreSQL's default port number to 5432 when running the `propel init` command. 3306 is actually MySQL's default port number.
http://www.postgresql.org/docs/9.4/static/runtime-config-connection.html
Have a nice day.
> Fix PostgreSQL's default port running the init command

- src/Propel/Generator/Manager/AbstractManager.php
The propel XML schema definition allows to reference external models,
which then are included the generation of the php source code. The
resulting classes can then be used in the application.
The 'referenceOnly' parameter indicates if the model should be included
in sql schema generation or not.
The current implementation does not check the value of this parameter,
it checks only if it is set. Because of a default value, the current
check evaluates always to true. This causes the sql generation to be
skipped.
> Fix referenceOnly bug

- src/Propel/Generator/Behavior/QueryCache/QueryCacheBehavior.php
- tests/Propel/Tests/Generator/Behavior/QueryCache/QueryCacheTest.php
Simple fix for #960. This one-liner updates this comparison to be consistent with other comparisons for this method.
> Alter comparison so that an int(-1) value for getLimit() evaluates correctly

- src/Propel/Generator/Behavior/Sortable/SortableBehaviorObjectBuilderModifier.php
- tests/Fixtures/bookstore/behavior-sortable-schema.xml
- tests/Propel/Tests/Generator/Behavior/Sortable/SortableBehaviorWithEnumScopeTest.php
- tests/Propel/Tests/Generator/Behavior/Sortable/TestCase.php
Here is a fix for the enum scope issue on Sortable behavior
It might not be perfect but at least it illustrates the issue and provides a test for it.
Here are the things that, to me, are arguable in this PR:
- I had to copy the regexp for the enum constants from the table map generator in the sortable generator
- I created the objects in the fixtures (you might prefer having them directly in the test case)
> Fix #954 - Sortable behavior on enum scope

- src/Propel/Runtime/Connection/StatementWrapper.php
Hi,
I find a bug in wrapper, if we execute PDO Statement with input_parameters into a debug context, the workaround for fetch getExecutedQueryString is based on boundValues (and in this case they don't set).
I propose following pull request for support this (with a silent fallback)
Best
> PDO Statement Wrapper not correctly return getExecutedQueryString with parameter

- bin/propel
`include('propel.php')` can include the propel configuration file, so an absolute path should be used.
> Use absolute path to include propel.php

- src/Propel/Generator/Command/SqlBuildCommand.php
Hi There
I ran into a situation where I have a behaviour thats part of of my main project, and when I ran the sql:build command, it complained about not being able to find my behaviour because it was using a different composer directory, and therefore wanted me to provide the composer-dir option (I have a fairly complex project structure, with modules and plugins). Upon adding the composer-dir option, Propel told me that it wasn't an option for the command sql:build. So upon inspecting the command, lone behold it doesn't exist. After adding it and running the sql:build command again with --composer-dir, everything worked as expected.
Im aware you are in the process of making a massive change with the internals of propel, but I'm offering this small fix anyway (in case someone ran into a …
> Added option --composer-dir to the sql:build command

- src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php
- tests/Propel/Tests/Issues/Issue915Book.php
- tests/Propel/Tests/Issues/Issue915Test.php
I did not find a good way to place the test fixture, so i included it in the testcases file.
> Fix #915  serialize custom properties in __sleep

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTest.php
Keeps timezone of original object. 
Previously, if you had `\DateTime` object in f.ex 'Europe/warsaw' timezone, as a result of `toArray` you received always Zulu timezone :)
> save timezone in result of toArray method

- src/Propel/Runtime/ActiveQuery/Criterion/BasicModelCriterion.php
Fails because of invalid usage of `strpos` function.
Throws an exception when `$this->clause` will be started with question mark, f.ex. `'? in (col1, col2, col3)'`
> fixed question mark recognition

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Reverse/PgsqlSchemaParser.php
Removed tables was not retrieved from the current database state.
Therefore the two variables ```$fromDatabaseTables``` and ```$toDatabaseTables``` had the same tables at the moment of the comparison in the DatabaseComparator...
> Fix no drop table and constraint when migrate:diff (PostgreSQL)

- src/Propel/Generator/Model/PropelTypes.php
- src/Propel/Generator/Platform/MssqlPlatform.php
- src/Propel/Generator/Reverse/MssqlSchemaParser.php
- src/Propel/Runtime/DataFetcher/PDODataFetcher.php
- tests/Propel/Tests/Generator/Platform/MssqlPlatformTest.php
This fix concerns reverse engineering, building sql files and creating sql migrations scripts.
It was needed to add support for `FETCH_ASSOC` in `PDODataFetcher` (see #863).
Also schema support for `GEOMETRY`column type was added.
Please be kind, this is my first contribution on GitHub ever :)
> Fix several errors when using mssql plattform

- src/Propel/Generator/Schema/Dumper/XmlDumper.php
I am working on a new SchemaParser using which the need for identifier quoting is detectable at the schema level. Without this PR however, the identifierQuoting attribute is not included in the reverse-engineered schema.xml
Let me know if there are any underlying reasons as to NOT include identifierQuoting.
Thanks
> Include identifierQuoting in the reverse-engineered schema.xml

- tests/Propel/Tests/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifierTest.php
Original commit message: Fixed php7 test suites
Fixes fatal error described in https://github.com/propelorm/Propel2/issues/1052
The following warnings remain:
```
PHP Warning:  The use statement with non-compound name 'VersionableBehaviorTest8' has no effect in /tmp/propelQuickBuild-2.0.0-dev-7a1e019deb/VersionableBehaviorTest8_VersionableBehaviorTest8Version.php on line 3136
PHP Warning:  The use statement with non-compound name 'VersionableBehaviorTest8Foo' has no effect in /tmp/propelQuickBuild-2.0.0-dev-7a1e019deb/VersionableBehaviorTest8_VersionableBehaviorTest8Version.php on line 3281
```
> Fixes fatal error in test suites.

- src/Propel/Generator/Command/MigrationCreateCommand.php
- tests/Propel/Tests/Generator/Command/MigrationTest.php
Fixes https://github.com/propelorm/Propel2/issues/832
For semantic reasons, I chose to implement it as a separate command instead of an "--empty" command to migration:diff.
Usage and verbose output:
```
"/app/dna/generated-migrations/PropelMigration_1449320135.php" file successfully created.
Now add SQL statements and data migration code as necessary.
Once the migration class is valid, call the "migrate" task to execute it.
```
> Added migration create command for creating empty migration classes

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectRelTest.php
Here is a fix for the Child deletion issue in many-to-one form issue.
Because this issue is caused mainly by Symfony not comparing the collection objects like Propel is made for, I unfortunately did not manage to provide any tests, though this fix does not break any existing ones...
> #968 - Fix the child deletion issue in many-to-one form

- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- tests/Propel/Tests/Issues/Issue829Test.php
whenever a key that could be serialized couldn't be casted to a `string` at the same time (f.in. `\DateTime`) an exception was thrown
fixes #829
> fixing serialization issues

- bin/propel.php
Don't need to redaclare $ns for every ReflectionClass.
Also avoid concat of '\\\\' in each iteration.
> optimize loop in propel.php

- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTest.php
1) Propel\Tests\Generator\Builder\Om\GeneratedObjectTest::testDefaultExpressions
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2015-12-10'
+'2015-12-11'
> Fixed sqlite test

- src/Propel/Generator/Builder/Util/SchemaReader.php
- tests/Propel/Tests/Generator/Builder/Util/SchemaReaderJoinSchemaTest.php
- tests/Propel/Tests/Generator/Builder/Util/barSchema.xml
- tests/Propel/Tests/Generator/Builder/Util/fooSchema.xml
This PR fix bug when `xml schema` split into several files and contains different `database schema`. Before this patch, propel will set the same schema for all tables.
> bug fix multiple 'XML Schema' with different 'database schema'

- tests/Propel/Tests/Common/Config/ConfigurationManagerTest.php
- tests/Propel/Tests/Common/Config/Loader/IniFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/JsonFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/PhpFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/XmlFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/YamlFileLoaderTest.php
- tests/bin/base.bat
- tests/bin/setup.mysql.bat
- tests/bin/setup.pgsql.bat
- tests/bin/setup.sqlite.bat
I made few adjustments for running unit tests on Windows machine. 
Tests are passing green without DB, with MySQL and with SQLite on Windows 7, PHP 5.6. 
---
PostrgreSQL however for some weird reason fails few tests - mostly because different quoting - looks like the Windows version ignores binding values as integers and treats them as strings instead. 
That leads to following type of errors:
```
Failed asserting that two strings are equal.
Expected :'INSERT INTO "group" ("id", "title", "as") VALUES (1, 'Test Group', 3)'
Actual   :'INSERT INTO "group" ("id", "title", "as") VALUES ('1', 'Test Group', 3)'
```
Any PostgreSQL expert who can give any insights? Is this some kind of known limitation or just misconfiguration? On linux, this works out of the box.
> Unit tests on Windows

- .gitignore
- src/Propel/Generator/Util/BehaviorLocator.php
- src/Propel/Runtime/Persister/SQL/SQLitePersister.php
- tests/Propel/Tests/Runtime/Persister/SQL/SQLitePersisterTest.php
SQLite keeps track of auto-increment fields in an internal table, called `sqlite_sequence`.
https://www.sqlite.org/fileformat2.html#seqtab
With this commit, `Propel\Runtime\Persister\SQL\SQLitePersister::readAutoIncrement` method
takes values from this table, preventing `FOREIGN KEY violation` errors.
This commit also provides a test, which failed with previous versions of the persister.
The previous algorithm, to read auto-increment fields, is still used if there's no `sqlite_sequence` table entry, for the given field.
> Fix Sqlite persister and Behavior locator

- README.md
- circle.yml
- composer.json
Since Propel2 is not tested against PHP-5.4 anymore (which is EOL), I updated the README and requirements. See 13a42b95c9175dcd90b27ee030106ac94eb919f9
> Update README.md, composer.json and circle.yml for PHP-5.5.

- src/Propel/Generator/Platform/MysqlPlatform.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformTest.php
- tests/Propel/Tests/Issues/Issue1115Test.php
- tests/Propel/Tests/Issues/Issue617Test.php
There are three commits in here. The first adds a test that proves https://github.com/propelorm/Propel2/issues/1115. The second fixes it by changing the way that Propel generates DDL statements for MySQL to always modify a table with a single big statement instead of many. This breaks lots of tests that were simply asserting on the exact DDL output. The third commit changes all those tests so that they pass again.
> Make MySQL table modifications always use one statement to fix total table-corruption bug #1115

- resources/dtd/database.dtd
- resources/xsd/database.xsd
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Generator/Model/Database.php
- src/Propel/Generator/Model/Table.php
- src/Propel/Generator/Schema/Dumper/XmlDumper.php
- tests/Propel/Tests/Generator/Model/DatabaseTest.php
I need to extends TableQuery objects with common methods, so I propose to add parameter similar to baseClass named parentClass for custom builder generator  extends "class name" ...
The class should extends ModelCriteria for be compatible (php doesn't support multiple extends)
> Proposal for implement a ParentClass for query objects at database or table level

- bin/propel.php
- src/Propel/Generator/Application.php
Xdebug being loaded reduces the runtime performance considerably (a factor up to 3). inform the user about it. refs #1066.
This was also a major problem when running composer, therefore we added this warning there like we do here.
see it in action: (Warning in the very first line after invoking the command)
> added a warning when xdebug is loaded in cli

- src/Propel/Runtime/Collection/ObjectCollection.php
- tests/Propel/Tests/Issues/Issue1133Test.php
Hello. I ran into a problem while using ObjectCollection. Subsequential use of `ObjectCollection::removeObject` and `ObjectCollection::append` results with wrong index mapping, which causes that improper items are removed and left in the collection.
I have provided simple test case to reproduce this issue.
It seems it is caused by optimistic assumption in `ObjectCollection::append` that `$pos = count($this->data);`
> Problem with ObjectCollection::removeObject

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Runtime/Parser/XmlParser.php
- src/Propel/Runtime/Util/PropelDateTime.php
- tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
In php5.5 added new interface for working with dates and a new class DateTimeImmutable, and now we can change DateTime class in the config on DateTimeImmutable
> Replace DateTime for DateTimeInterface

- src/Propel/Generator/Behavior/Sluggable/SluggableBehavior.php
When a `scope_column` is present in the config of the behaviour the `$getter` gets overwritten which breaks things.
> Fix $getter mixup in sluggable behaviour generator

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
references issue #1137 
$ php -d 'memory_limit=4G' vendor/bin/phpunit --verbose
Tests started in temp /tmp.
PHPUnit 5.2.10 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.0.3 with Xdebug 2.4.0RC4
Configuration: /home/damien/Propel2/phpunit.xml
....SS.......................................................   61 / 3358 (  1%)
.............................................................  122 / 3358 (  3%)
.............................................................  183 / 3358 (  5%)
.............................................................  244 / 3358 (  7%)
.............................................................  305 / 3358 (  9%)
.............................................................  366 / 3358 ( 10%) …
> BaseModel::save(): call $this->preSave() before fetching $this->isNew()

- src/Propel/Common/Config/PropelConfiguration.php
This fixes a problem in which propel always tried to connect with empty username/password for all read queries
> Added user and password options to the slaves configuration

- tests/Propel/Tests/Generator/Model/SchemaTest.php
The Behavior class does not have a method called `hasBehavior`.
> fixed SchemaTest

- src/Propel/Generator/Builder/Om/ClassTools.php
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
This fix prevents propel to generate duplicated methods such as isDeleted() or isNew()
The getters will still be available via getIsDeleted() etc.
> Prevented function redeclaration error by skipping reserved methods

- src/Propel/Generator/Builder/Om/templates/baseObjectMethodHook.php
Please find join a proposal for support baseClass Object default implementation for pre/post callback (save/update/delete)
> Callback (pre/post, save/update/delete) implementation in base Object

- src/Propel/Runtime/Map/ColumnMap.php
I work on propel with identifierQuoting="true" and I try to make a propel query with join field = A.b : 
$query->withColumn($field) or sorting by join field or where condition with join field
I have an issue on find() method because in Criteria::createSelectSql propel try to fetch columnName and tableName and try to link to TableMap column definition, in this case ColumnMap::normalizeName() for explode and fetch column name however with identifierQuoting true the field is convert to `A`.`b` so TableMap::getColumn() fail on hasColumn `b` because the column name is b (without quote)
My workaround is to remove all kind of escaping quote ` for mysql, ' for mssql with trim function (we shouldn't have space too) in normalize function, this can be more elegant with an "unquote" adapter method or …
> Use complex field in select with join if identifierQuoting="true"

- tests/bootstrap.php
- slug behavior should force utf8 locale for assure iconv tranlit behavior (bootstrap.php not apply here)
- if user is root file "unreadable" checks should be skipped
> slug behavior and root user tests suite fix

- src/Propel/Generator/Behavior/Versionable/VersionableBehavior.php
- tests/Propel/Tests/Generator/Behavior/Versionable/VersionableBehaviorTest.php
As mentioned in issue #824  versionble behavior was generating the version table with duplicate prefix.
Table was changed the call method Table::getName() and replaced by Table::getOriginCommonName()
And finally been implemented tests for database with tablePrefix.
> Fix versionable behavior

- src/Propel/Common/Config/PropelConfiguration.php
Without this, it throws:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Unrecognized option "facility" under "propel.runtime.log.defaultLogger"   
```
At runtime, without this configuration option, it throws:
```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Unknown facility value "" given' in /vendor/monolog/monolog/src/Monolog/Handler/AbstractSyslogHandler.php:88
```
... when using "syslog" configuration.
> Fixing `PropelConfiguration` for syslog'ing.

- src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
- tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
Fix similar problem like https://github.com/propelorm/Propel2/pull/1171 (Fix versionable behavior)
The archivable behavior duplicate the table prefix.
The generated class name has a table prefix name, for example:
- tablePrefix: `foo_`
- table name: `bar`
- generated class: `FooBarArchive` and `FooBarArchiveQuery`
I think the generated class name should be `BarArchive` and `BarArchiveQuery`
> Fix archivable behavior

- src/Propel/Generator/Model/Domain.php
The input `$size` argument should convert to int, otherwise the `diff` command will check incorrectly.
When `Propel/Generator/Model/Diff/ColumnComparator` checking the column size propery, the `$fromDomain->getSize()` is a `int` type, and the `$toDomain->getSize()` is a `string`type.
https://github.com/propelorm/Propel2/blob/b511db089c7ff4f3353e75db49fb6870b3a656b1/src/Propel/Generator/Model/Diff/ColumnComparator.php#L58-L60
```php
if ($fromDomain->getSize() !== $toDomain->getSize()) {
$changedProperties['size'] = [ $fromDomain->getSize(), $toDomain->getSize() ];
}
```
> force input size type to int when using `replaceSize`

- src/Propel/Generator/Manager/MigrationManager.php
It is easier to add a phpdoc to tell the `$manager` parameter's class name
> Add phpdoc for "MigrationManager" parameter

- src/Propel/Generator/Command/DatabaseReverseCommand.php
- src/Propel/Generator/Command/InitCommand.php
- src/Propel/Generator/Manager/ReverseManager.php
- src/Propel/Generator/Model/ScopedMappingModel.php
- tests/Propel/Tests/Generator/Command/DatabaseReverseTest.php
- tests/Propel/Tests/Generator/Model/DatabaseTest.php
Fixes #1201 by placing the namespace (given by the user) into schema.xml when reverse engineering an existing database.  Also replaces the unused `schemaAutoNamespace` configuration option with the currently used `generator.schema.autoNamespace` propel configuration option.
> Add ability to use specified namespace in propel init command

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
During model:build time this error may be encountered when using imported tables without PK.
> Added proper Exception when encountering a table without PK.

- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
$realFullColumnName may be either table.field or schema.table.field so the correct $realColumnName is always the last field of the exploded array and not the second.
> Inconsistent behavior between join and joinWith leading to malformed on clause

- src/Propel/Generator/Config/GeneratorConfig.php
- src/Propel/Runtime/Connection/PdoConnection.php
Pull request related to issue https://github.com/propelorm/Propel2/issues/1185
This allows to pass specific PDO options such as MYSQL_ATTR_SSL_KEY
> Pass specific driver options to PDO constructor

- src/Propel/Generator/Command/MigrationCreateCommand.php
- src/Propel/Generator/Command/MigrationDiffCommand.php
- src/Propel/Generator/Manager/MigrationManager.php
- tests/Propel/Tests/Generator/Command/MigrationTest.php
It is rather hard to find a certain migration with the current filenames:
```
PropelMigration_1456744599.php
PropelMigration_1457186710.php
PropelMigration_1457212222.php
PropelMigration_1458157955.php
PropelMigration_1461870141.php
PropelMigration_1462121943.php
PropelMigration_1462860381.php
PropelMigration_1462946617.php
PropelMigration_1463383579.php
PropelMigration_1464338765.php
```
This PR allows an optional suffix to be specified when creating migrations, so that the filenames directly hint at what the migrations contain:
```
PropelMigration_1456744599_import_process_data_model_enhancements.php
PropelMigration_1457186710_user_entry_rows_cascade_delete.php
PropelMigration_1457212222_data_model_correction.php
PropelMigration_1458157955_transaction_row_additional_booleans.php …
```
> Added possibility to decorate generated migration files with a custom suffix

- src/Propel/Runtime/DataFetcher/PDODataFetcher.php
PDODataFetcher can have null data object (after close by example) and rewinded (dump by example) 
=> tests avoid exception
> PDODataFetcher can have null data object and throw exception

- src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
- tests/Propel/Tests/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifierTest.php
Issue #774 
Fix versionable behavior when exists 2 connected tables, versionable behavior in both tables and parameter version_column is changed.
---
* Fix versionable when exists custom field on table with FK
* Implementing tests
---
> Fixed versionable behavior

- src/Propel/Common/Config/PropelConfiguration.php
- src/Propel/Generator/Command/AbstractCommand.php
- src/Propel/Generator/Command/GraphvizGenerateCommand.php
- src/Propel/Generator/Command/MigrationCreateCommand.php
- src/Propel/Generator/Command/MigrationDiffCommand.php
- src/Propel/Generator/Command/ModelBuildCommand.php
- src/Propel/Generator/Command/SqlBuildCommand.php
Following up on #519 : 
I'd like to propose a pull request to be able to use/set the `recursive` option from the configuration file(s)
```
#example propel.yml
propel:
generator:
recursive: true
```
> [generator] Making recursive schema configurable trough config file(s)

- src/Propel/Runtime/Util/PropelDateTime.php
- tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
It came to my attention that PropelDateTime::createHighPrecision can return "false" when the numeric format for floats is changed by setting specific locales. For example in the locale "de_DE" floats will be formatted with a "," (comma) as decimal pointer. This will result in a "false" from DateTime::createFromFormat.
I submitted a patch, just replacing a "," with a "." in the value of "microtime(true)".
> Locale-independent functionality of PropelDateTime::createHighPrecision

- src/Propel/Runtime/Util/PropelDateTime.php
just like in the newInstance
timezone must be explicitly specified and then changed
because of a DateTime bug: http://bugs.php.net/bug.php?id=43003
> specify timezone in PropelDateTime::createHighPrecision

- src/Propel/Generator/Reverse/PgsqlSchemaParser.php
I discovered it was the migration, but in fact the problem is PgsqlSchemaParser. For up to version 9.4 the command  **show search_path** returns:
```SQL
|    search_path |
|----------------|
| "$user",public |
```
From the postgreSQL version 9.5 we have the result.
```SQL
|    search_path  |
|-----------------|
| "$user", public |
```
Just only one space and everything explodes.
So I removed the spaces at the time of reading the schemas :smiley: 
The **TravisCI** is not ready for **PostgreSQL9.5** why not add it in .travis.yml(travis-ci/travis-ci#4264). Not ready without sudo.
> Fix schemaname for PostgreSQL 9.5

- src/Propel/Runtime/Util/PropelDateTime.php
... to match the expected 'U.u' format in createHighPrecision(). (#1257)
> Ensuring that PropelDateTime::getMicrotime() includes the fractional part

- tests/bin/phpunit.agnostic.sh
- tests/bin/phpunit.mysql.sh
- tests/bin/phpunit.pgsql.sh
- tests/bin/phpunit.sqlite.sh
Allows to use [the command-line arguments when running phpunit tests](https://phpunit.de/manual/current/en/textui.html)
> Phpunit boot scripts accepts command line arguments

- src/Propel/Generator/Builder/Om/QueryBuilder.php
> Fixes: PHPDoc wrong for auto-usage of LIKE when '*' or '%' found

- src/Propel/Generator/Behavior/Timestampable/TimestampableBehavior.php
This restores the possibility of using Timestampable behavior with INTEGER column to store an unix timestamp, which has been broken recently.
> Allows the use of TimestampableBehavior with INTEGER columns

- src/Propel/Generator/Platform/MssqlPlatform.php
Previously these used DATETIME, but then propel tried to insert just a date or time into the database, resulting in a error "[S0001][241] Conversion failed when converting date and/or time from character string."
> Update to use TIME & DATE types

- src/Propel/Generator/Platform/MssqlPlatform.php
DATETIME timestamps are limited to 3 digit precision, where DATETTIME2 allows 7 digits. The timestampable behavior needs this precision. 
Example of types: 
datetime	2007-05-08 12:35:29.123
datetime2	2007-05-08 12:35:29. 1234567
> Use DATETIME2 to allow high precision timestamps

- src/Propel/Generator/Command/InitCommand.php
the extra space was causing the below error when using an absolute path like /home/my.app.sq3
Unable to connect to the specific sql server: SQLSTATE[HY000] [14] unable to open database file
> removing leading space within the sqlite dsn

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectArrayColumnTypeTest.php
For arrays containing only `0`, the getter currently returns an empty array.
> array columns getter: return correct value for `[0]`

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
The proposed solution for #1310
> Check 'alreadyInSave' before save transaction

- src/Propel/Runtime/Collection/Collection.php
- tests/Propel/Tests/Runtime/Collection/ObjectCollectionTest.php
The test I add was failing with:
```
Propel\Runtime\Exception\BadMethodCallException: Call to undefined method: hashCode
/home/peter/dev/Propel2/src/Propel/Runtime/Collection/Collection.php:558
/home/peter/dev/Propel2/src/Propel/Runtime/Collection/ObjectCollection.php:496
/home/peter/dev/Propel2/src/Propel/Runtime/Collection/ObjectCollection.php:496
/home/peter/dev/Propel2/src/Propel/Runtime/Collection/ObjectCollection.php:485
/home/peter/dev/Propel2/tests/Propel/Tests/Runtime/Collection/ObjectCollectionTest.php:277
```
because `ObjectCollection.php:496` calls `hashCode()` on itself with:
```
if (is_object($object) && is_callable([$object, 'hashCode'])) {
return $object->hashCode();
}
```
The test returns `true` because `Collection.php` has a `__call()` method. It then fails because that …
> Fix regression in ObjectCollection of Collections.

- src/Propel/Runtime/Map/TableMapTrait.php
Fix translateFieldNames method in Propel/Runtime/Map/TableMapTrait.php.
Bug: if key == 0(id in my case) field name does not translated.
> fix TableMapTrait.php

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectWithDateImmutableClassTest.php
When using [configuration](http://propelorm.org/documentation/reference/configuration-file.html#datetime-settings) like:
```
dateTime:
useDateTimeClass: true
dateTimeClass: DateTimeImmutable
```
The base objects `toArray` method is unable to process the `DateTimeImmutable`, because its checking directly for `\DateTime`, the current patch makes it use `DateTimeInterface` instead.
> Fixed Base\Object::toArray when using DateTimeImmutable from configuration

- src/Propel/Common/Config/XmlToArrayConverter.php
- tests/Propel/Tests/Common/Config/DataProviderTrait.php
- tests/Propel/Tests/Common/Config/XmlToArrayConverterTest.php
Implemented via the existing functionality in PHP's DOMDocument object.
Additionally libxml_disable_entity_loader(true) is not necessary any
longer (it prevented opening XML files from disc earlier) since Oct 2012
with the release of libxml2 version 2.9.0.
The old code looked influenced by the (earlier to that date) hotfix in
the Symfony project however the XXE attack Symfony was prone to, did not
apply to the XmlToArrayConverter (no validate on parse).
Refs:
- #1321
- https://www.w3.org/TR/xinclude/
- https://mail.gnome.org/archives/xml/2012-October/msg00045.html
> Support XML Inclusions in configuration, adds #1321

- src/Propel/Generator/Platform/MysqlPlatform.php
(stupid) example:
```xml
<column name="metricIdStart"      phpName="MetricIdStart" type="integer"            required="true" expose="true">
<vendor type="mysql">
<parameter name="Unsigned" value="true"/>
</vendor>
</column>
<column name="metricIdEnd"        phpName="MetricIdEnd"   type="integer"            required="true" expose="true">
<vendor type="mysql">
<parameter name="Unsigned" value="false"/>
</vendor>
</column>
```
Will yield the following SQL
```mysql
`metricIdStart` INTEGER UNSIGNED NOT NULL,
`metricIdEnd` INTEGER NOT NULL,
```
I did no check upon column type when processing Unsigned attribute to keep the code simple, I wonder if I should test it and raise an exception if not applicable to current column type?
> Allows the use of Unsigned="true|false" as a MySQL vendor column parameter

- src/Propel/Common/Config/Loader/FileLoader.php
- tests/Propel/Tests/Common/Config/Loader/FileLoaderTest.php
getenv() returns a string response, which may be an empty string.
This is a valid response and may represent, for example, and empty db password variable (DB_PW).
The patch is to check if getenv() returned false in order to determine if an error occurred or not.
* The same check is used in [TestCaseFixtures.php (line 101)](https://github.com/propelorm/Propel2/blob/618c192272b5bc9636412659bf32bd572910b819/tests/Propel/Tests/TestCaseFixtures.php#L101)
> Allowing file loader to accept empty env vars (e.g. DB_PW)

- src/Propel/Common/Config/Loader/IniFileLoader.php
Hello,
I'm using *master*, and I was trying to configure the following in ```propel.properties``` (or ```propel.ini```) : 
```ini
propel.generator.recursive = true
propel.generator.namespaceAutoPackage = false
propel.generator.packageObjectModel = true
```
but it triggers the following : 
```sh
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]                    
Invalid type for path "namespaceAutoPackage". Expected boolean, but got integer.
```
Tested with PHP 5.6.21 and php 7.0.14.
> Fix broken boolean types on IniFileLoader (propelorm/Propel2#1355)

- src/Propel/Generator/Model/Table.php
- src/Propel/Runtime/Util/PropelDateTime.php
- tests/Fixtures/bookstore/schema.xml
- tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
- tests/Propel/Tests/Issues/Issue675Test.php
Propel should not allow incomplete foreign key references when foreign
table has a composite primary key.
https://github.com/propelorm/Propel2/issues/675
> Check incomplete foreign-keys #675

- src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
Fixes an issue with the `applyLimit` in the MssqlAdapter incorrectly splitting the query string when inner select statements are included. 
Example use case:
```php
$projects = ProjectQuery::create()
->where('Project.ProjectID IN (
SELECT InstanceID FROM RBAC.dbo.InstanceTemp
)')
->offset(10)
->limit(10)
->find();
```
> MSSQL `applyLimit` Greedy Regex Fix

- src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/MssqlAdapterTest.php
Corrections for #1381, as well as a new regression test class `MssqlAdapterTest` to cover them. 
I'm not sure if temporarily changing the default adapter for the tests was the right approach, but I couldn't find another way to effectively test using `ModelCriteria`. I'm open to alternative suggestions.
> Fix detection of subquery virtual columns in MssqlAdapter::applyLimit

- src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/MssqlAdapterTest.php
Fixes regression issue found after PR #1382 was merged in. Now correctly identifies `FROM` as a keyword versus `FROM` as part of a column name.
> Fix MssqlAdapter::applyLimit from generating malformed queries when `from` is included as a non-keyword

- composer.json
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectJsonColumnTypeTest.php
Previously, when using JSON Type for a column, every setXXX() on this column would result in a modified column.
This PR adds a check between old JSON and new value, as objects.
> Fix json equality check

- README.md
It is recommended to write hashes only on the left side, not wrapping the title up.
And this also fixes the trailing single hash behind title.
> Remove tailing hashes

- src/Propel/Generator/Reverse/MysqlSchemaParser.php
In mariadb 10.2 `CURRENT_TIMESTAMP` is replaced by`current_timestamp()` in `SHOW COLUMNS FROM my_table`
> Fix issue #1406 : diff issue with CURRENT_TIMESTAMP on maria 10.2

- .travis.yml
PHP 7.2 now is RC2, and will we need support 7.2, but we have bugs for this
> Added php 7.2 in travis

- resources/xsd/database.xsd
I use this xsd file in my IDE and it always complains, that the referenceOnly-attribute 'is not allowed here', even though it is [0]. Thats why I would like this to be merged :)
[0]: http://propelorm.org/documentation/reference/schema.html#external-schema-element
> Added referenceOnly attribute to external-schema

- src/Propel/Runtime/Collection/OnDemandCollection.php
This fixes fatal errors with PHP 7.2.
> Make offsetGet compatible with the parent's offsetGet method

- src/Propel/Runtime/ActiveQuery/InstancePoolTrait.php
Address failed tests after applying fix for issue #1425 which is ralated to the countable issue in php 7.2.
I think the issue is related to the fact that the fix added the condition: is_numeric($pk) && $pk > 1 to the if, which is not present in the previous releases, which then caused some tests to start failing.
> Address failed tests after applying fix for issue #1425

- src/Propel/Generator/Builder/Om/TableMapBuilder.php
In the generated TableMap, the `getPrimaryKeyFromRow` method gave an error when using a custom `phpType`. This is fixed by only casting to the php type if its not an custom object type. In that case, use the contstructor. Fixes #926
> Fix getPrimaryKeyFromRow for custom php types

- src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php
- tests/Propel/Tests/Issues/Issue1463Test.php
When constructing a MySQL LIMIT clause, values for the offset and limit are coerced to integers. This prevents arbitrary SQL from being injected via a query limit. Example:
```php
UserQuery::create()->limit('1;DROP TABLE users')->find();
```
Previously, this would have injected `DROP TABLE users` into the generated SQL. Now, the limit value would be coerced to the integer `1`.
Fixes #1463
> SQL injection fix: Coerce offset and limit values to integers for MySQL LIMIT clause

- src/Propel/Runtime/ActiveQuery/Criteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
This is a followup to a [fix for SQL injections with LIMIT clauses in MySQL](https://github.com/propelorm/Propel2/pull/1464). That fix only applied to the MySQL adapter, and other existing or future adapters could still be at risk.
By coercing limit inputs to integers upon setting them, we can avoid SQL injection vulnerabilities with `limit()` across all database adapters.
The original code comments implied that integer coercion could be problematic with 32-bit integers, but unit tests in this PR prove otherwise. Even 64-bit integers seem to work fine.
> SQL injection fix: Cast limit to integer when setting via Criteria::setLimit()

- src/Propel/Generator/Model/MappingModel.php
- src/Propel/Generator/Platform/DefaultPlatform.php
- src/Propel/Runtime/ActiveQuery/Join.php
implode() should be called with `glue` first to support php 7.4  
[see here](https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix)
> Rearrange implode() arguments where necessary to conform to php7.4

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/templates/baseObjectMethodHook.php
The calls to parent hooks should only be generated if that class has a base class, otherwise the static analyser complains about the use of "parent", when there is no parent.
> Only generate calls to parent hooks, if the class being generated has a base class

- .travis.yml
Refs https://github.com/propelorm/Propel2/issues/1521
package should be bumped to 5.6+ in composer and docs as well, no point maintaining 5.5 anymore here.
Lots of fails though still in Travis that require fixing.
There seem to now surface more severe issues, as well:
> Class 'Symfony\Component\Translation\IdentityTranslator' not found
Follow up tasks
> Update to PHP74 travis and simplify matrix.

- src/Propel/Runtime/Connection/ConnectionManagerMasterSlave.php
- src/Propel/Runtime/Connection/ConnectionManagerPrimaryReplica.php
- tests/Propel/Tests/Common/Config/ConfigurationManagerTest.php
- tests/Propel/Tests/Runtime/Connection/ConnectionManagerMasterSlaveTest.php
- tests/Propel/Tests/Runtime/Connection/ConnectionManagerPrimaryReplicaTest.php
Spryker would like to start using primary/replica functionality of Propel.
We would like to have this change first, though. It keeps naming consistent with modern tech like aws rds https://aws.amazon.com/rds/features/read-replicas/
> Use term primary/replica instead, deprecate in BC way.

- tests/Propel/Tests/Generator/Builder/Om/GeneratedQueryObjectColumnTypeTest.php
In order to unblock the PHP7.4, SF5 dependencies on projects and start gathering more collaborative feedbacks on their incompatibility I'm disabling LIKE validation on objects (cool, but not documented capability). We recover it later.
> Split out LIKE condition on objects, which is buggy in php74

- .travis.yml
Fixes: https://github.com/propelorm/Propel2/issues/1570
Uses a deprecated unix distro because it's the only one from Travis that actually works with maria 10.1, everyone else using travis-ci fixed this with custom hacks or docker.
> Adds Maria 10.1

- composer.json
Refs https://github.com/propelorm/Propel2/issues/575
We should get all to psr-4 including tests (which currently are not yet in autoloader at all)
This would probably be for the 2.0 stable release.
> Use PSR-4 now.

- src/Propel/Runtime/Adapter/Pdo/SqliteAdapter.php
phpstan reports
>  Call to sprintf contains 0 placeholders, 1 value given.  
%i seems indeed invalid
I wonder if there were no tests for this so far.
> Fix SQLite sprintf() error

- .travis.yml
prefer lowest should fail the built if they fail.
~~Also removed non-minimal prefer lowest as they have no additional value~~
we now still run 42 jobs, which we could further limit down
but this is probably a fair compromise for now
> Remove prefer lowest from allow failure

- composer.json
- src/Propel/Generator/Command/AbstractCommand.php
- src/Propel/Generator/Command/ConfigConvertCommand.php
- src/Propel/Generator/Command/DatabaseReverseCommand.php
- src/Propel/Generator/Command/GraphvizGenerateCommand.php
- src/Propel/Generator/Command/InitCommand.php
- src/Propel/Generator/Command/MigrationCreateCommand.php
- src/Propel/Generator/Command/MigrationDiffCommand.php
- src/Propel/Generator/Command/MigrationDownCommand.php
- src/Propel/Generator/Command/MigrationMigrateCommand.php
- src/Propel/Generator/Command/MigrationStatusCommand.php
- src/Propel/Generator/Command/MigrationUpCommand.php
- src/Propel/Generator/Command/ModelBuildCommand.php
- src/Propel/Generator/Command/SqlBuildCommand.php
- src/Propel/Generator/Command/SqlInsertCommand.php
- src/Propel/Generator/Command/TestPrepareCommand.php
Start to resolve 
- https://github.com/propelorm/Propel2/issues/1574
- https://github.com/propelorm/Propel2/issues/1573
- https://github.com/propelorm/Propel2/issues/1578
by
- adding Symfony5
- dropping EOL versions to simplify the very broad dependency spectrum
- using proper semver on this low level
Now only PHPUnit is outdated and needs in the future to go to 8+
This is what we should be supporting moving forward
Now we just need to start fixing the issues showing up.
EDIT: I will rebase mine on top of https://github.com/propelorm/Propel2/pull/1595 now.
> Finish Symfony 5 support.

- .editorconfig
- .gitattributes
- .travis.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon
- src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php
- src/Propel/Generator/Behavior/Versionable/VersionableBehaviorQueryBuilderModifier.php
This is now removed from allow_failure list and part of normal travis run.
I also added docblocks to allow IDE discovery (auto complete / typehinting) as well as PHPStan to check those.
> Add PHPStan level 1 check with baseline until we can remove symf2.

- src/Propel/Common/Config/PropelConfiguration.php
This was implemented in early 2017 (see https://github.com/php/php-src/commit/247ce052cd0fc7d0d8ea1a0e7ea2075e9601766a), and is very useful for self-signed certificates.
> Allow option MYSQL_ATTR_SSL_VERIFY_SERVER_CERT to be set

- src/Propel/Generator/Reverse/MysqlSchemaParser.php
MariaDB 10.3.4 introduced system-versioned tables (https://mariadb.com/kb/en/temporal-data-tables/).
There is a known issue (possibly a bug) that can cause issues for ORM tools like Propel, described here: https://jira.mariadb.org/browse/MDEV-16857?focusedCommentId=117570&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-117570
"ORM tool will be confused as the primary key definition in the database doesn't match the one defined in application code after system versioning is enabled."
Basically, system versioning creates an invisible primary key that shows up with "SHOW KEYS FROM table" but not with "SHOW COLUMNS FROM table". This PR fixes that by skipping these invisible primary key columns when generating the schema.
> Fix issue where propel reverse breaks with system-versioned tables

- .travis.yml
There is no point having 3 tests display the same fail
Once this is solved in a few months we can and will enable full coverage here again.
> Remove nightly except one

- src/Propel/Generator/Command/MigrationMigrateCommand.php
https://github.com/propelorm/Propel2/pull/1595/files#diff-1ccdce29404b8984d1b2101f0069a564R84
it looks like this change was "correct in the sense of what was before and the transition towards int",
as false means 1 (error)
But if you look more deeply the already existing false should have been true (and thus 0) as return value.
This code, if no migration has to be done, should actually say "all good" and not report an error here.
//cc @Incognito
> Fix return value for "no migration needed" case

- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
> PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /home/travis/build/propelorm/Propel2/src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php on line 538
Warning: Private methods cannot be final as they are never overridden by other classes in /home/travis/build/propelorm/Propel2/src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php on line 538
> Fix PHP8 warning.

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/BookstoreTest.php
Example database:
```xml
<table name="book" description="Book Table">
<column name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER" description="Book Id" />
<column name="title" type="VARCHAR" required="true" description="Book Title" primaryString="true" />
<column name="author_id" required="false" type="INTEGER" description="Foreign Key Author" />
<foreign-key foreignTable="author" onDelete="setnull" onUpdate="cascade">
<reference local="author_id" foreign="id" />
</foreign-key>
</table>
<table name="author" description="Author Table">
<column name="id" required="true" primaryKey="true" autoIncrement="true" type="INTEGER" description="Author Id" />
<column name="first_name" required="true" type="VARCHAR" size="128" description="First Name" />
<column …
```
> Do not try to fetch related objects of new object

- src/Propel/Generator/Platform/PgsqlPlatform.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/OraclePlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/PgsqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/PgsqlPlatformTest.php
- tests/Propel/Tests/Generator/Platform/PlatformMigrationTestProvider.php
- tests/Propel/Tests/Generator/Platform/PlatformTestProvider.php
Unique indices are currently generated in two different ways:
- "getAddTableDDL" creates it over an unique constraint
- "getAddIndexDDL" creates it without unique constraint
The Problem is, that the method "getDropIndexDDL" will remove unique indices always by constraint.
> always create unique indices by constraint (for pgsql platform)

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
Currently, the generated code is
public function getUpdatedAt($format = NULL)
which is not quite according to standards (see bool true/false etc).
Also rector complains here and attempts to fix these things.
> Fix NULL to null for object builder.

- src/Propel/Common/Util/SetColumnConverter.php
- src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
- src/Propel/Runtime/Connection/TransactionTrait.php
- tests/Propel/Tests/Runtime/Connection/TransactionTraitTest.php
fixes #1653
Situation that is being fixed:
```php
$con = Propel::getConnection('some_connection');
try
{
$con->transaction(function() {
throw new \Error('boom');
});
}
// my code is handling both errors and exceptions and can continue doing its work ...
catch (\Throwable $throwable)
{
// .. yet we're now in a never-ending transaction
assert(false === $con->inTransaction()); // this assertion fails
}
```
> Fixes transaction handling when \Throwable is thrown

- composer.json
- config/phpcs.xml
Fix travis by excluding unfixable rule for now
Revert requires PHP8 fixes ( https://github.com/propelorm/Propel2/pull/1645 ) to be resolved/merged.
> Fix travis.

- composer.json
Lowering the requirements for `symfony/*` libs from  4.3+ to 4.0+.
According to current dependencies definitions in `composer-symfony4-min.json` tests of such are passing:
https://github.com/propelorm/Propel2/blob/3087361bd27f3598f3ecd70e9fd272a5c2575b88/tests/composer/composer-symfony4-min.json#L20-L26
https://travis-ci.org/github/propelorm/Propel2/jobs/726959500
> Compatibility with Symfony 4.0+ instead of 4.3+

- src/Propel/Generator/Model/MappingModel.php
This dead section was correctly identified by PHPstan: empty `$stringValue` arguments would have been handled by the section in line 148-150, and `explode` with any string value will always return an array with at least one element. Minimal example:
```php
php > var_dump(explode(',', ''));
array(1) {
[0]=>
string(0) ""
}
```
> Remove dead code

- phpstan-baseline.neon
- src/Propel/Runtime/ActiveQuery/Criteria.php
- src/Propel/Runtime/ActiveQuery/Lock.php
- src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
- src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php
- src/Propel/Runtime/Adapter/Pdo/OracleAdapter.php
- src/Propel/Runtime/Adapter/Pdo/PgsqlAdapter.php
- src/Propel/Runtime/Adapter/Pdo/SqliteAdapter.php
- src/Propel/Runtime/Adapter/SqlAdapterInterface.php
- tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/MysqlAdapterTest.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/OracleAdapterTest.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/PgsqlAdapterTest.php
This PR adds ability for locking reads, either shared or exclusive
Compatibility with:
- [MySQL 5.6+](https://dev.mysql.com/doc/refman/5.6/en/innodb-locking-reads.html)
- [PostgreSQL 8.1+](https://www.postgresql.org/docs/8.1/sql-select.html#SQL-FOR-UPDATE-SHARE)
Example:
```php
$booksReadInShareMode = (new BookQuery)
->filterById(123)
->forShare()
->find();
// SELECT ... FROM book LOCK IN SHARE MODE -- mysql
// SELECT ... FROM book FOR SHARE -- pgsql
$booksToBeUpdated = (new BookQuery)
->filterById(123)
->forUpdate()
->find();
// SELECT ... FROM book FOR UPDATE
```
> Locking reads

- src/Propel/Runtime/Connection/StatementWrapper.php
- tests/Propel/Tests/Runtime/Connection/PropelPDOTest.php
#1611 introduced [faulty handling of `StatementWrapper::setFetchMode()`](https://travis-ci.org/github/prgTW/Propel2/jobs/742558255#L638-L642)
```php
<?php
$pdo = new PDO('sqlite::memory:');
$pdo->query('CREATE TABLE dummy(id int)');
$stmt = $pdo->prepare('SELECT * FROM dummy');
$stmt->setFetchMode(PDO::FETCH_ASSOC, null, array()); // shouldn't render any errors
// fix
// $stmt->setFetchMode(PDO::FETCH_ASSOC); // only 1 argument passed
```
ref: https://3v4l.org/fniRF
no warning or exception
PHP >=8.0:
> Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: fetch mode doesn't allow any extra arguments
PHP <8.0:
> Warning: PDOStatement::setFetchMode(): SQLSTATE[HY000]: General error: fetch mode doesn't allow any extra arguments
- `PdoStatement::setFetchMode()` passes the same …
> [BUGFIX] PdoStatement::setFetchMode compatibility

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Model/MappingModel.php
While working on an increasingly heavy type-hinted codebase I noticed that the propel property accessors/mutators frequently omit the `|null` return/param typehint. This PR resolves that and allows projects using Propel2 to accurately perform static analysis on propel properties.
Edit 2020-11-05: I added the changes from PR #1669 to get the build green.
Fixes #1669
> Add null-typehint for nullable property accessors/mutators

- src/Propel/Runtime/Connection/ConnectionInterface.php
After https://github.com/propelorm/Propel2/pull/1654 was introduced, docblocks in interface and implementation were not aligned with each other.
> Fixes docblock for transaction function

- .github/workflows/ci.yml
- composer.json
- phpstan-baseline.neon
- src/Propel/Runtime/Collection/CollectionIterator.php
Make Propel2 compatible with PHP 8 (well, it's already compatible: just few adjustments).
~~Test suite is green but the new version of PhpStan raises some esotheric (for me) errors: could you suggest me, please, how to fix them?~~
I added some composer scripts, if you don't like I can remove them, of course.
> Introduce PHP 8

- src/Propel/Generator/Util/QuickBuilder.php
- src/Propel/Generator/Util/VfsTrait.php
- tests/Propel/Tests/Common/Config/ConfigurationManagerTest.php
- tests/Propel/Tests/Common/Config/Loader/IniFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/JsonFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/PhpFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/XmlFileLoaderTest.php
- tests/Propel/Tests/Common/Config/Loader/YamlFileLoaderTest.php
- tests/Propel/Tests/Common/Config/XmlToArrayConverterTest.php
- tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php
- tests/Propel/Tests/Generator/Model/DatabaseTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Util/QuickBuilderTest.php
- tests/Propel/Tests/Runtime/Parser/AbstractParserTest.php
Refactor`QuickBuilder` to build classes on virtual filesystem.
This commit introduces the following differences:
-  The built classes are grouped in a single file and written on virtual filesystem, by default. Optionally, it's possible to write them on physical filesystem, for debugging purpose. When we use the physical filesystem, the classes are written in separated files, to make the debug easier. E.g.:
```php
<?php
use Propel\Generator\Util\QuickBuilder;
$schema = '<database>.............</database>';
//---The following builds on virtual filesystem
$builder = new QuickBuilder();
$builder->build($schema);
// or alternatively
QuickBuilder::buildSchema($schema);
//---The following builds on physical filesystem
$builder = new QuickBuilder();
$builder->setVfs(false); …
```
> QuickBuilder refactor

- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- src/Propel/Runtime/ActiveQuery/Criteria.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Issues/Issue1420Test.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
fixes #1420
---
- 3 models defined in DB: A, B, C
- A hasOne/hasMany B
- A hasOne/hasMany C
Making a query for A models with B models hydrated and merging criteria for the same base model having "with" models (here: C model)
```php
$aModels = (new AQuery)
->leftJoinWith('B');
->mergeWith((new AQuery)->leftJoinWith('C'))
->find();
```
```sql
SELECT
a.id, a.a_field, -- A fields
b.id, b.a_id, b.b_field, -- B fields
a.id, a.a_field, -- A fields again
c.id, c.a_id, c.c_field -- C fields
FROM a
LEFT JOIN b ON (a.id = b.a_id)
LEFT JOIN c ON (a.id = c.a_id)
```
- model A hydrated properly
- model B hydrated properly
- model C hydrated improperly
`PDODataFetcher::getIndexType` is `TableMap::TYPE_NUM` so object hydration relies on the order of the columns in `SELECT` part.
At the beginning the …
> Fixes invalid hydration when using mergeWith of criteria with "with" models

- src/Propel/Generator/Builder/Om/QueryBuilder.php
I noticed that the generated query classes had an incorrect return type specified for the `findOne` and `findOneBy*` methods. These methods can return `null`, getting static analysis confused.
> Update findOne model overrides: nullable return

- src/Propel/Runtime/ActiveQuery/Criteria.php
I'm getting thousands of "PHP Notice:  Undefined index: column" in server logs.
There is no guarantee that createSelectSql($params) will add those keys in $params, so, protecting access to those keys.
> Avoid "Undefined index: column" in Criteria.php

- src/Propel/Generator/Builder/Om/QueryBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
The `withXyzQuery` function neatly wraps the calls to `useQuery` and `endUse`
in a single function call, taking a callable working on the correct
subquery type.
Projects using propel2 can use it like this:
```php
$bookQuery
->withAuthorQuery(
fn (AuthorQuery $q) => $q->filterByFirstName('Lev')
)
->filterByTitle('Anna Karenina');
```
without type checkers like phpstan and psalm getting confused about the
actual return type of `endUse()`.
An extra `@phpstan-param` phpdoc line is provided for static type
checkers to check whether the argument to the callable and the return
type actually match.
> Add `withXyzQuery` function to aid static type checking

- psalm-baseline.xml
- src/Propel/Common/Config/Loader/FileLoader.php
- src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
- src/Propel/Generator/Behavior/Sluggable/SluggableBehavior.php
- src/Propel/Generator/Builder/Util/SchemaReader.php
- src/Propel/Generator/Model/Diff/DatabaseComparator.php
- src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php
- src/Propel/Runtime/Collection/Collection.php
- src/Propel/Runtime/Collection/CollectionIterator.php
- src/Propel/Runtime/Connection/StatementInterface.php
With PHP8 and potential use of named arguments, we need to more closely follow core naming of method variables, especially when overriding or extending core classes or interfaces.
I also fixed up some variable naming to proper casing.
> Fix up interface method signature for PHP8+. Fix variable naming.

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
Please refer to the Psalm documentation for conditional types[^0] for
more information. Although the docs specify that template parameters are
required, the reference-a-variable shorthand for templates also work,
see the [example].
Usually this project seems to prefer `@phpstan-`-prefixes, but this
construct is currently not available to PHPstan[^1].
[^0]: https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/
[^1]: https://github.com/phpstan/phpstan/issues/3853
[example]: https://psalm.dev/r/11cdedd7b3
> Add parameter-dependent psalm return type hint to temporal accessors

- tests/Propel/Tests/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifierWithScopeTest.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectWithFixturesTest.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedQueryDoDeleteTest.php
- tests/Propel/Tests/Generator/Builder/Om/QueryBuilderInheritanceTest.php
- tests/Propel/Tests/Generator/Migration/BaseTest.php
- tests/Propel/Tests/Issues/Issue829Test.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/QuotingTest.php
- tests/Propel/Tests/Runtime/Connection/PropelPDOTest.php
- tests/Propel/Tests/Runtime/Util/TableMapTest.php
Some of the tests were "risky" when they did not perform any assertions, and phpunit cluttered the output with warning. Most of them check there is no exception, so I marked them with `@doesNotPerformAssertions`. Two tests were not finished, so I added `$this->markTestIncomplete();`.
One test failed with MySQL because it did not account for MySQL 8, which removed display size for int (as in INT(4), see https://stackoverflow.com/questions/60892749/mysql-8-ignoring-integer-lengths). Simple fix is to use VARCHAR instead.
Two tests failed with MySQL (and probably with Oracle, too) because of `Expression of SELECT list is not in GROUP BY clause`. I think this is a bug in Propel, which should not force users to change server mode, but since these tests are about something else, I only change …
> Tests cleanup

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/FieldnameRelatedTest.php
Just when I thought I was done with Propel.
In general, methods of ActiveRecods are chainable, but `->fromArray()` isn't, meaning you have to write:
```php
$book = BookQuery::create()->findPk($id); // get the object reference
$book->fromArray($data);            // call void method
$book->setChanger($userId)->save();           // finish
```
when you could just do:
```php
BookQuery::create()
->findPk($id)
->fromArray($data)
->setChanger($userId)
->save();
```
Some people prefer the former, which is fine, and they can still use it, but lots of folks prefer the latter, lean version, and it is consistent with the other setters.
There really is no reason why the first one should be disallowed.
> Make fromArray() chainable (aka return $this)

- src/Propel/Runtime/Connection/ConnectionWrapper.php
- src/Propel/Runtime/Util/Profiler.php
- tests/Propel/Tests/Runtime/Util/ProfilerTest.php
When using the Profiler to check time and memory usage, php shows three notices:
> **Notice**: Undefined index: microtime in **vendor/propel/propel/src/Propel/Runtime/Util/Profiler.php** on line **242**
> **Notice**: Undefined index: microtime in **vendor/propel/propel/src/Propel/Runtime/Util/Profiler.php** on line  **253**
> **Notice**: Undefined index: memoryUsage in **vendor/propel/propel/src/Propel/Runtime/Util/Profiler.php** on line  **261** 
The problem is outlined [here](https://github.com/propelorm/Propel2/pull/1647#issuecomment-801380568).
If merged, this replaces #1647
> Bugfix: remove undefined index notice from profiler

- tests/Propel/Tests/Generator/Command/MigrationTest.php
During #1719, the migration command tests broke my test database several times to the point where I had to reset the database. My fault, obviously, but they are written very Ctrl+C/Ctrl+V, and quite fragile. Got frustrated and cleaned them up.
> cleanup of migration tests

- src/Propel/Runtime/ActiveQuery/Criteria.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- src/Propel/Runtime/Map/TableMap.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
- tests/Propel/Tests/Runtime/Map/TableMapTest.php
Ok, so this drove me nuts for quite a while. When using aliases and regular column names (i.e. a.name instead of a.Name), queries broke horribly, as Propel inserted these columns with a cross join.
Example:
```php
$c = new ModelCriteria('bookstore', 'Propel\Tests\Bookstore\Book');
$c->setModelAlias('b', true);
$c->where('b.title = ?', 'foo');    // note: using title, not Title
$c->join('b.Author a');
$c->where('a.first_name = ?', 'john'); // note: using first_name, not FirstName
```
led to query
```sql
SELECT  
FROM book b 
CROSS JOIN book     -- nooooooo
CROSS JOIN author   -- noooooooooooooo
INNER JOIN author a ON (b.author_id=a.id) 
WHERE b.title = :p1 AND a.first_name = :p2'
```
Same happened with regular query objects. 
Turns out, around line 2100 in ModelCriteria.php, where column …
> Bugfix: table alias and regular column name leads to cross join

- src/Propel/Generator/Command/MigrationDiffCommand.php
If we show the names of uncommitted migrations it makes debugging more easy
> [DX] Show names of uncommitted migrations

- src/Propel/Runtime/Map/TableMap.php
- tests/Propel/Tests/Runtime/Map/TableMapTest.php
Tests & fixes for #1660, #1713: Simply make sure that `getCollectionClassName()` returns a class extending `Collection`, otherwise bad things can happen.
If merged, this replaces #1660, #1713
> Tests & Fixes for #1660, #1713 - Bugfix: getCollectionClassName() should only return Collection classes

- phpstan-baseline.neon
- psalm-baseline.xml
- src/Propel/Generator/Manager/MigrationManager.php
- src/Propel/Generator/Manager/templates/migration_template.php
- tests/Propel/Tests/Generator/Manager/MigrationManagerTest.php
Found some stuff while cleaning up my project, that other might find useful.
This changes the migration files to use heredoc instead of string literals. The advantage is that you can copy lines from and to a database editor, without having to quote/unquote strings, which I had to do a lot for more complex migrations.
I also moved the migration template from the generating code into its own file, similar to other Propel templates.
With this change, migrations look like this:
```php
public function getUpSQL()
{
$connection_default = <<< 'EOT'
ALTER TABLE `payment`
CHANGE `status` `status` set('granted','denied','in_submission', 'deleted') NOT NULL;
EOT;
return array(
'default' => $connection_default,
);
}
```
instead of:
```php
public function getUpSQL()
{
return array (
'default' => ' …
```
> Feature: use heredoc in migration file

- phpunit.xml.dist
- tests/Propel/Tests/Generator/Migration/MigrationTestCase.php
- tests/Propel/Tests/Generator/Migration/PrimaryKeyAITest.php
- tests/Propel/Tests/Runtime/Adapter/Pdo/MysqlAdapterTest.php
Played around with the tests a bit and fixed some things:
1. Updated the phpunit.xml.dist to get rid of the warning when starting phpunit:
```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```
Basically, they changed how code coverage tool configuration is done. New version works (tested it with phpunit/php-code-coverage).
2. When running the test in the mysql group, a migration test failed because it uses the integer display with property (as in INTEGER(2)), which was removed in MySQL 8.0.19 (see [here](https://stackoverflow.com/questions/60892749/mysql-8-ignoring-integer-lengths/60892835#60892835)). The test is now skipped on MySQL
3. Updated a MySQL-only test, that used an …
> Test fixes - update phpunit.xml.dist and MySQL 8 fixes

- src/Propel/Runtime/Collection/ObjectCollection.php
- tests/Propel/Tests/Runtime/Collection/ObjectCollectionTest.php
Another day, another merge request. Hope this isn't unwelcome.
This is a small one: Calling `ObjectCollection->populateRelation()` does not reset the partial flag, which leads to consecutive queries on an already initialized relation. So if a data object with a partially loaded relation is retrieved from instance pooling, `populateRelation()` loads the relation data, but when accessing the data, another reload is triggered.
Simple example:
```php
$book = BookQuery::create()
->leftJoinWithAuthor() // will create a partially loaded book relation on autor object
->findOne();
$authors = AuthorQuery::create()->find(); // already loaded author object will be retrieved from cache 
$authors->populateRelation('Book'); // loads all books
$book->getAuthor()->getBooks(); // loads books again when …
```
> Bugfix: reset partial flag when populating a relation

- phpstan-baseline.neon
- src/Propel/Runtime/ActiveQuery/Criteria.php
- tests/Propel/Tests/Runtime/Util/TableMapExceptionsTest.php
Failed queries are shown with placement variables in the Exception:
```
Unable to execute UPDATE statement [UPDATE payment SET receiver_id=:p1, date_changed=:p2 WHERE payment.id=:p3]
```
That makes it often hard to see what went wrong.
To see the database error, you have to check the log:
```
Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'receiver_id' cannot be null
```
The query did not go to the log, but at least it is possible to puzzle together what went wrong.
However, there is a nice formatter available, which writes full queries to the log.
New Exception message looks like this:
```
Unable to execute statement [UPDATE payment SET receiver_id=NULL, date_changed='2021-04-28 22:15:55.450739' WHERE payment.id=1491]
Reason: [SQLSTATE[23000]: Integrity constraint …
```
> Show failed queries and SQL error in debug mode exception

- phpstan-baseline.neon
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
- src/Propel/Runtime/ActiveQuery/Criterion/ExistsCriterion.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/Criterion/ExistsCriterionTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/ExistsTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/ExistsTestClasses.php
- tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
Did you realize, there is no possibility to do EXISTS in Propel, except through `->where('EXISTS (...))`, which has its own caveats (buggy, no query logic). So I had a look at how this probably should work, and it actually went ahead pretty quickly.
These changes allow to create exist queries in two ways:
First one is through regular useQuery logic, same as with the other high-level Propel statements. The relation condition is added to the inner query (in the example author.Id = book.author_id):  
```php
BookQuery::create()
->useAuthorExistsQuery()    // or ->useExistsQuery('Author')
->filterBy...
->endUse()
```
Second one is more basic, where a nested query is set as exists query. Here, any table can be used, but the filter in the exists-query must be added manually:
```php
$existsQuery …
```
> Feature: Add exists operator

- src/Propel/Runtime/Connection/ConnectionInterface.php
- src/Propel/Runtime/Connection/ConnectionWrapper.php
- src/Propel/Runtime/Connection/PdoConnection.php
- src/Propel/Runtime/Connection/StatementWrapper.php
- tests/Propel/Tests/Runtime/Connection/ConnectionWrapperTest.php
- tests/Propel/Tests/Runtime/Connection/PropelPDOTest.php
- tests/Propel/Tests/Runtime/Connection/StatementWrapperTest.php
When a query fails during execution, only the exception message is written to log, not the query itself. That makes it hard to figure out what went wrong from the log.
With this fix, an exception is stored and then rethrown after logging. The query cannot be logged before execution, as this would give wrong execution time and memory usage in the Profiler.  
I fixed an error in `PdoConnection::exec()`. This is likey not a big deal, since it only fixes something that was broken, but you might want to check because of **backwards compatibility**, hence the double highlighting.
The `PdoConnection::exec()` method wraps `PDO::exec()`, which, according to the [manual](https://www.php.net/manual/en/pdo.exec.php) "does not return results from a SELECT statement". Instead, it returns the number of …
> Bugfix: Failed queries should be written to log & Fix PdoConnection::exec()

- src/Propel/Generator/Command/InitCommand.php
- tests/Propel/Tests/Generator/Command/InitCommandTest.php
Ok, this is really menial. Still annoyed me after seeing it a million times. Ever wondered what is going on with that one console output ('Successfully wrote PHP configuration in file "/tmp/propel_init/generated-conf/config.php"') during tests?
The one around 39%:
```
> phpunit --colors=always
Tests started in temp /tmp.
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.
.....SS......................................................   61 / 3548 (  1%)
.............................................................  122 / 3548 (  3%)
.............................................................  183 / 3548 (  5%)
.............................................................  244 / 3548 (  6%)
.............................................................  305 / 3548 (  8%) …
```
> propagate output interface in init command

- src/Propel/Generator/Reverse/MysqlSchemaParser.php
- src/Propel/Runtime/DataFetcher/PDODataFetcher.php
- tests/Propel/Tests/Generator/Reverse/AbstractSchemaParserTest.php
- tests/Propel/Tests/Generator/Reverse/MysqlSchemaParserTest.php
- tests/Propel/Tests/Runtime/Formatter/DataFetcherTest.php
Added tests for #1507, which adds an import of column and table descriptions during `database:reverse` on a MySQL database.
Also, while writing the tests, I again missed `PDODataFetcher::fetchAll()` (the class has a `fetch()` method, and in general just wraps PDO methods), so I added it in its own commit (didn't want to put it into its own PR, as I need it in the tests).
If merged, #1507 can be closed.
> Tests for #1507: Import MySQL column/table descriptions during database:reverse & added PDODataFetcher::fetchAll()

- tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
- tests/Propel/Tests/Runtime/ActiveQuery/JoinTest.php
- tests/Propel/Tests/Runtime/Util/TableMapTest.php
- tests/mysql.phpunit.xml
- tests/pgsql.phpunit.xml
- tests/sqlite.phpunit.xml
Had this lying around, it's just some cleanup in tests:
- Updated the phpunit.xml files for mysql, postgres and sqlite to current phpunit format
- A test was skipped with the message "Famous cross join problem, to be solved one day". Obviously, I couldn't resist - what mystery and excitement would await me? The answer is that join type defaults to inner join (in `Join::getJoinType()`), so you will not end up with a cross join when you omit the type. Bit of a letdown to be honest. No need to call Nancy Drew.
- Also stumbled over a unstructured and repetitive (and misplaced) test of the join class in CriteriaTest, which I removed, and instead added to JoinTest  the parts that were not covered before.
It's all pretty random, but it is probably still better to have it than not.
> Misc test fixes

- phpstan-baseline.neon
- src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
- src/Propel/Generator/Manager/ReverseManager.php
- src/Propel/Generator/Model/Database.php
- src/Propel/Generator/Model/ScopedMappingModel.php
- src/Propel/Generator/Model/Table.php
- src/Propel/Generator/Schema/Dumper/XmlDumper.php
- tests/Propel/Tests/Generator/Builder/Om/AbstractOMBuilderNamespaceTest.php
- tests/Propel/Tests/Generator/Model/DatabaseTest.php
- tests/Propel/Tests/Generator/Model/TableTest.php
- tests/Propel/Tests/Resources/blog-database.php
- tests/Propel/Tests/Resources/blog-database.xml
- tests/Propel/Tests/Resources/blog-schema.xml
Lots of users, including me, have stumbled over doubled namespaces after `database:reverse` (see #1233). For example, calling `prople database:reverse --namespace=My\Namespace ...` will lead to a schema like
```xml
<database namespace="My\Namespace">
<table PhpName="MyTable" namespace="My\Namespace">
</table>
</database>
```
which will generate files in the namespace `My\Namespace\My\Namespace`, not the specified `My\Namespace`, and hence the confusion.
The reason for this is actually quite straight forward. Propel differentiates between absolute namespaces and relative namespaces (as documented [here](http://propelorm.org/documentation/cookbook/namespaces.html#namespace-declaration-and-inheritance)). Absolute namespaces begin with a backslash, while relative namespaces do not. So if …
> fix doubly namespaces during database:reverse / write absolute namespaces to schema.xml

- src/Propel/Generator/Behavior/AggregateMultipleColumns/templates/objectCompute.php
- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- src/Propel/Generator/Builder/Om/templates/tableMapClearRelatedInstancePool.php
- tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
I am getting errors in the generated map- and model-files when using AggregateMultipleColumnsBehavior with single quotes in the filter condition. Problem is that strings are written to file without escaping those quotes.
In the model-file, it is a problem with the behavior, when the SQL query is not escaped.
In the map-file, it is a problem with the TableMapBuilder, which only escapes in arrays.
Also, `addGetBehaviors()` function in TableMapBuilder replaced all spaces in stringified arrays, probably to adjust the format of `var_export`. Because, what could go wrong...
Also a newline was missing at the beginning of the template added after the `getBehaviors()` function.
I did not change AggregateColumnsBehavior, even though it suffers from the same problem. Reason is that it would break …
> Bugfix: Escape quotes in behavior 

- src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- src/Propel/Generator/Model/Table.php
- tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
- tests/Propel/Tests/Generator/Builder/Om/TestableQueryBuilder.php
I want to mark a table abstract, since it is only used for inheritance:
```xml
<table name="person" skipSql="true" abstract="true">...</table>
```
But the classes built from that schema have errors in them. Marking a table abstract seems to do exactly two things, both cause errors with PHP.
Current behavior 1: The user model class is set to abstract
Introduced problem: The query class is still set to instantiate objects from a now abstract class, which is not allowed
Proposed solution: If table is abstract, calling methods that usually create instances (`findPkSimple()`) throw an exception (unless when the table uses  concrete_inheritance, which creates instances from other classes).
Current behavior 2:  In the table map, set `OM_CLASS` to empty string and make the function `getOMClass()` …
> Bugfixes for abstract tables

- psalm-baseline.xml
- src/Propel/Common/Config/PropelConfiguration.php
- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- src/Propel/Generator/Builder/Om/TableMapLoaderScriptBuilder.php
- src/Propel/Generator/Builder/Om/templates/tableMapLoaderScript.php
- src/Propel/Generator/Command/ConfigConvertCommand.php
- src/Propel/Generator/Command/ModelBuildCommand.php
- src/Propel/Generator/Command/TestPrepareCommand.php
- src/Propel/Generator/Config/ArrayToPhpConverter.php
- src/Propel/Generator/Manager/ModelManager.php
- src/Propel/Generator/Util/QuickBuilder.php
- src/Propel/Runtime/Map/DatabaseMap.php
- src/Propel/Runtime/ServiceContainer/ServiceContainerInterface.php
- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
- tests/Propel/Tests/Generator/Config/ArrayToPhpConverterTest.php
- tests/Propel/Tests/Runtime/ServiceContainer/StandardServiceContainerTest.php
This PR fixes the issue with missing table registration when using PHP 7.4 preloading (see #1695).
This is a big one, and I am not sure how much I like it. But there is probably no way around it.
- Instead of relying on automatic registration of tables, which does not work with preloading, the tables are now registered explicitly through a script.
- Script creation and importing is done in a way where it does not impact existing projects.
- However, users have to rebuild their configuration and their models with the `config:convert` and `model:build` command.
- If they are not aware of that, exceptions will tell them what to do.
The metadata for tables is stored in table map files, which are generated by the `model:build` command (i.e. BookTableMap.php). They are registered in database …
> Add table map initializer

- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
- tests/Propel/Tests/Runtime/ServiceContainer/StandardServiceContainerTest.php
In order to reduce confusion and resulting bug reports about an outdated configuration or missing database import, I have created a howto page in the Propel2 wiki at https://github.com/propelorm/Propel2/wiki/Exception-Target:-Loading-the-database, and I have added the URL to the exception message.
I am not sure if the wiki is the correct location, but I am not sure if the official documentation is still maintained, so the wiki seems like the next best thing. Please let me know if the howto should go somewhere else. I'd prefer a perma link
> add howto url to missing loader script exception

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
In the query baseclass generator, some `@psalm-method` lines were used,
because PHPstan doesn't support prefixed `@method`-annotations currently
(2021-07-12). The two tools have a good history of supporting each
other's prefixes, so chances are that PHPstan will pick up the `@psalm-` prefixed
annotations in the future.
> Add phpstan- prefixed ObjectCollection&\Traversable<> annotations

- src/Propel/Generator/Platform/DefaultPlatform.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectDateColumnTypeTest.php
In our system, we sometimes use `9999-12-31` as a special 'until end of time' value for date-columns. (We're developing against MySQL, which has `9999-12-31` as maximum for date columns. However, if the `DateTime` object accidentally had a time component, this would cause the column to overflow.
This PR contains a fix for this issue, ensuring that DATE columns will be inserted into the database in the `Y-m-d` format, dropping the time-component which is not expected on columns with a native DATE type.
> Format insert DATE values as Y-m-d instead of 'Y-m-d H:i:s.u'

- phpstan.neon
- psalm.xml
- src/Propel/Common/Config/PropelConfiguration.php
After this PR the new way is already used for sf 4.2 - 4.4, to avoid the deprecation notice.
> PropelConfiguration: avoid deprecation notice

- src/Propel/Runtime/ActiveQuery/Criteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
With the latest `master` build we ran into the problem that `COUNT(*)`-queries to our `order` table failed. This patch ensures that the setting for identifier quoting is properly observed.
Note that I deliberately ignored the `getSql` helper-function in the test, as this behaviour is precisely what the `getSql` helper-function hides.
> Quote primary table name if identifier quoting is enabled

- src/Propel/Generator/Builder/Om/TableMapBuilder.php
- tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
We use concrete-inheritance for our 'setting' table[1], and encountered the buggy situation in which we had application crashes on development environments (lots of branch-switching) where a recently-introduced type present in the database would instantiate a nonexisting class.
This patch defaults the behaviour of `SettingQuery()->find()` to return the base class for unknown types, instead of `Package\\Setting`, by using the (correctly-namespaced) classname in `TableMap::OM_CLASS`.
I added a test that verifies that the base class name is returned from `TableMap::getOMClass()` with an unexpected value.
[1]: example column.
```xml
<column
name="type"
type="ENUM"
required="true"
default="string"
valueSet="'string','int','boolean','datetime','country'"
inheritance="single"
>
<inheritance …
```
> Allow default-value for concrete-inheritance to be instantiable

- src/Propel/Common/Pluralizer/StandardEnglishPluralizer.php
- tests/Propel/Tests/Common/Pluralizer/EnglishPluralizerTest.php
Time to fix some old bug-reports!
Although the [Jargon File](http://www.catb.org/jargon/html/B/boxen.html) suggests that 'Boxen' should be a valid pluralisation 😜
> [#1284] pluralise 'Box' to 'Boxes'

- config/phpcs.xml
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/TableMapBuilder.php
Fixes #1638
I chose not to to the 'each class in its own file' rule as suggested in the referenced issue, as test files are currently not covered by the PHPCS checks.
> BC break: rename functions with underscores for PSR2 compat

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- tests/Propel/Tests/Common/BoxedString.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTest.php
Sometimes we use boxed primitives for types that have more specific semantics than just `string` or `int`. This allows us to define methods on the boxed primitives, enabling greater class coherence.
However, entities with boxed primitives are always reported as 'does not have only default values', because the `hasOnlyDefaultValues` function uses `!==`. Generally this is a good idea, but for objects this compares the _references_ instead of the _contents_.
This patch inspects the default-value initialiser for 'starts with `new `', as a proxy for 'is this an object type'.
There's a test to validate this behaviour. I validated that the test fails with the unpatched `ObjectBuilder` code.
> Use object-equality instead of reference-equality to compare object properties

- phpstan-baseline.neon
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
Fixes #1317
I have tried to add a test for this in `tests/Propel/Tests/Generator/Behavior/ConcreteInheritance/ConcreteInheritanceBehaviorTest.php`, but because of the on-the-fly generated classes I was not able to override the constructor of `ConcreteContentSetPk`.
> 1317-parent-constructor

- src/Propel/Generator/Builder/Om/TableMapBuilder.php
Our 'symfony debug autoloader' was spamming messages for every generated `TableMap`-class on every request. This patch should bring the typehint of the generated `TableMap` implementations in line with the typehint of the base class
> Add return-typehint for generated buildRelations, to bring it in line with the base class typehint

- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/PropelQueryTest.php
Added the `isSelfSelected` property to the `Propel\Runtime\ActiveQuery\ModelCriteria::clear()` method to avoid an empty select SQL statement after the `clear()` method was executed.
> Added `isSelfSelected` property to the `clear` method

- psalm.xml
Symfony 6 added return types to most of it's signatures.
This is reported as ReservedWords by Psalm.
See https://github.com/vimeo/psalm/issues/7026 and https://github.com/doctrine/dbal/pull/5053 for more context.
> Workaround null & mixed being ReservedWords

- composer.json
- src/Propel/Runtime/Connection/ConnectionWrapper.php
When looking into dependencies, it becomes clear that psr/log v1 is required due to a require-dev (optional) dependendy locking it
We need to prevent this in order to fully test both our min and max promise.
As such, this PR aims to fix it properly - and replaces https://github.com/propelorm/Propel2/pull/1819
Completes https://github.com/propelorm/Propel2/pull/1805
With this PHP7 folks are using psr/log v1, PHP8 folks can use psr/log v2/v3 already.
> Allow Monolog v2 to enable psr/log v2/v3

- src/Propel/Generator/Builder/Om/templates/baseObjectMethodHook.php
This is possible because doSave and delete doesn't use any
return value from those functions.
> Post{Save,Insert,Update,Delete} methods returns nothing

- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
What should I do with the lying Docblock?
> ModelCriteria::getPreviousJoin() may return null

- src/Propel/Generator/Config/ArrayToPhpConverter.php
- src/Propel/Runtime/Connection/ConnectionManagerPrimaryReplica.php
- src/Propel/Runtime/Connection/ConnectionManagerSingle.php
- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
- tests/Propel/Tests/Runtime/Connection/ConnectionManagerMasterSlaveTest.php
- tests/Propel/Tests/Runtime/Connection/ConnectionManagerPrimaryReplicaTest.php
- tests/Propel/Tests/Runtime/Connection/ConnectionManagerSingleTest.php
- tests/Propel/Tests/Runtime/ServiceContainer/StandardServiceContainerTest.php
This is forced using a constructor.
Also, StandardServiceContainer::setManager() no longer have the manager name
as first argument but retrieve it from the manager itself.
> Ensure ConnectionManagerInterface::getName() always return a string

- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
- src/Propel/Runtime/ActiveQuery/ModelCriteria.php
- tests/Propel/Tests/Runtime/ActiveQuery/PropelQueryTest.php
I started to work with the new type hints in Propel (very nice!), but ran into some problems with return types:
* The return type of `Query::find()`, `Query::findByXyz()` and `Query::findPks()` is set to ObjectCollection, but it returns ArrayCollection if `->select()` is used
* Docstring of temporal types (`Model::getDate()`) says that method can return null on non-null columns
* Method `Model::isPrimaryKeyNull()` is declared to return a bool, but no return is added if the table has no primary key
Particularly the last two are pretty menial, but it cannot hurt to adjust it.
Also fixed an error from phpstan, where a string was used as a class name without check if the class exists.
> Adjust return type of Query::find methods

- src/Propel/Common/Util/PathTrait.php
Replace "strpos" with "strrpos" to find the last occurrence of src folder.
> Fix #1884 - Incorrect path of template folder

- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
Small update to the recent changes around enabling debug mode: when enabling or disabling, connections need to be closed, otherwise old connection will be used and change does not apply.
> close connections when changing debug mode

- src/Propel/Runtime/Collection/Collection.php
- src/Propel/Runtime/Collection/CollectionIterator.php
- src/Propel/Runtime/Collection/IteratorInterface.php
- src/Propel/Runtime/Collection/OnDemandCollection.php
- src/Propel/Runtime/Collection/OnDemandIterator.php
`OnDemandCollection::getIterator` docblock has not compatible type with the base class. Added a common type for both classes
> Added a common return type for Collection::getIterator() method

- src/Propel/Generator/Behavior/I18n/I18nBehaviorObjectBuilderModifier.php
- src/Propel/Generator/Builder/Om/AbstractObjectBuilder.php
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Model/PropelTypes.php
- src/Propel/Generator/Platform/MssqlPlatform.php
- src/Propel/Generator/Platform/MysqlPlatform.php
- src/Propel/Generator/Platform/OraclePlatform.php
- src/Propel/Generator/Platform/PgsqlPlatform.php
- src/Propel/Generator/Platform/SqlitePlatform.php
- src/Propel/Generator/Reverse/MysqlSchemaParser.php
- src/Propel/Generator/Reverse/SqliteSchemaParser.php
- src/Propel/Generator/Util/QuickBuilder.php
- src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php
- src/Propel/Runtime/Map/ColumnMap.php
- tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTemporalColumnTypeTest.php
- tests/Propel/Tests/Generator/Migration/BaseTest.php
- tests/Propel/Tests/Generator/Platform/DefaultPlatformTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformTest.php
This allows to use column type DATETIME.
At the moment, while Propel handles DATETIME correctly in schema.xml and generates the expected migrations, building the model will lead to an error:
>   Error setting up column receipt_date: Cannot map unknown Propel type 'DATETIME' to native database type. 
Instead, the type "TIMESTAMP" has to be used, which is fine for almost all DBMS, since usually only one datetime/timestamp type is available anyway.
However, in MariaDB, both types are available and they are notably different in that they support different date ranges, and that MariaDB sets default values for the first timestamp in a table (see [here](https://mariadb.com/kb/en/timestamp/#automatic-values)), making TIMESTAMP the type to use if you want to timestamp the row, while DATETIME is …
> allow datetime type columns

- tests/composer/composer-symfony4-max.json
- tests/composer/composer-symfony4-min.json
- tests/composer/composer-symfony5-max.json
- tests/composer/composer-symfony5-min.json
- tests/composer/composer-symfony6-max.json
- tests/composer/composer-symfony6-min.json
I think this fixes the error currently occurring when running tests on gitlab:
```
Error: dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
You can run "composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)
See https://getcomposer.org/allow-plugins
In PluginManager.php line 769:
dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin w  
hich is blocked by your allow-plugins config. You may add it to the list if  
you consider it safe.                                                       
You can run "composer config …
```
> fix pipelines (missing allow-plugins in composer.json)

- src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
- tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
Resolves #1894 
Please let me know, if we can write tests for this behavior depending on different platforms.
Without the fix, test setup will fail because of the error described in the linked issue.
To keep it more simple, we could also discuss to never copy the original's index name which might be a breaking change if someone relies on the archive index name.
> Fix invalid duplicate indices using ArchivableBehavior for some platforms

- src/Propel/Generator/Builder/Om/TableMapLoaderScriptBuilder.php
- src/Propel/Generator/Manager/AbstractManager.php
- src/Propel/Generator/Model/Table.php
- src/Propel/Generator/Reverse/SqliteSchemaParser.php
- src/Propel/Generator/Util/QuickBuilder.php
- src/Propel/Generator/Util/VfsTrait.php
- src/Propel/Runtime/Connection/ConnectionFactory.php
- src/Propel/Runtime/Map/DatabaseMap.php
- src/Propel/Runtime/ServiceContainer/ServiceContainerInterface.php
- src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php
- src/Propel/Runtime/Util/Profiler.php
- templates/Builder/Om/tableMapLoaderScript.php
- tests/Propel/Tests/Runtime/Map/DatabaseMapTest.php
This MR changes the way tables are registered during initialization to improve performance. Instead of building the internal table lookup structure by accessing static class properties of the table classes, the table lookup is loaded directly from the init file.
During initialization, available database tables are registered in Propel. Currently this is done through the qualified class name (i.e. `\Propel\Tests\BookstoreSchemas\Map\BookTableMap`), which is handed to a `DatabaseMap`, which then adds it to its table lookup maps. There are two kinds of lookup, access by name (schema and table name, i.e. `bookstore_schemas.book`) or by PHP name (either set in schema.xml or generated from name, i.e. `\Book`).
Currently, the lookup maps are created by accessing static properties of the supplied …
> load databases without accessing classes

- templates/Builder/Om/baseQueryClassHeader.php
Dang it, I missed a few places when moving the query class docblock into the template. Here is the fix. Sorry.
> docblock query class fixes

- .github/workflows/ci.yml
- tests/bin/setup.pgsql.sh
While playing around with the postgres tests, I stumbled over having to enter the database password three times every time I ran the setup script, even though I provided the password in the designated `DB_PW` variable.
This can be remedied by registering connection in a `.pgpass` file or setting the `PGPASSWORD` variable, but having to change the system to run tests seamlessly should not be necessary. Fortunately, the issue can easily be addressed in the setup script. All we need to do is setting postgres' `PGPASSWORD` variable to the password in `DB_PW` before running dropdb, createdb and psql. I do that in a subshell, so the value of `PGPASSWORD` in the actual shell is not altered.
That's it, no more triple password prompt.
The gitlab workflows used the `DB_PW`+`PGPASSWORD` approach, …
> setup postres tests without password prompt

- src/Propel/Generator/Model/Column.php
- src/Propel/Generator/Model/PropelTypes.php
- src/Propel/Generator/Platform/MssqlPlatform.php
- src/Propel/Generator/Platform/MysqlPlatform.php
- src/Propel/Generator/Platform/OraclePlatform.php
- src/Propel/Generator/Platform/PgsqlPlatform.php
- src/Propel/Generator/Platform/SqlitePlatform.php
- src/Propel/Generator/Reverse/AbstractSchemaParser.php
- src/Propel/Generator/Reverse/MssqlSchemaParser.php
- src/Propel/Generator/Reverse/OracleSchemaParser.php
- src/Propel/Generator/Reverse/PgsqlSchemaParser.php
- src/Propel/Generator/Reverse/SqliteSchemaParser.php
- src/Propel/Runtime/ActiveQuery/Criteria.php
- src/Propel/Runtime/ActiveQuery/SqlBuilder/InsertQuerySqlBuilder.php
- src/Propel/Runtime/ActiveQuery/SqlBuilder/UpdateQuerySqlBuilder.php
- src/Propel/Runtime/Map/ColumnMap.php
- tests/Propel/Tests/Generator/Model/ColumnTest.php
- tests/Propel/Tests/Generator/Platform/MssqlPlatformTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformTest.php
- tests/Propel/Tests/Generator/Platform/OraclePlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/OraclePlatformTest.php
- tests/Propel/Tests/Generator/Platform/PgsqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/PgsqlPlatformTest.php
- tests/Propel/Tests/Generator/Platform/PlatformMigrationTestProvider.php
- tests/Propel/Tests/Generator/Platform/PlatformTestProvider.php
- tests/Propel/Tests/Generator/Platform/SqlitePlatformTest.php
- tests/Propel/Tests/Generator/Reverse/PgsqlSchemaParserTest.php
- tests/bin/setup.mysql.sh
- tests/bin/setup.pgsql.sh
As discussed in #1914, this allows to use `UUID` as column type in schema.xml. Underlying columns are set to the native uuid type of the database system (`uuid` in Postgres and Oracle, `UNIQUEIDENTIFIER` in mssql). In Mysql/MariaDB and SQLite, an error is thrown. Inside the model and query classes, the uuid columns use string values.
This is pretty straight forward, a new type literal is registered and associated with strings, and register the type in the vendor adapters with the corresponding type. For Postgres, I added cast statements used during migration. Tests check generated `create` and `alter` statements and internal mapping of uuid to string.
I have played around with it on Postgres, and it seems to work there.
I also added a commit with two fixes for the test setup scripts:
- …
> Add support for native UUID column type

- tests/Propel/Tests/Generator/Command/InitCommandTest.php
- tests/Propel/Tests/TestCaseFixtures.php
- tests/bin/setup.mysql.sh
- tests/bin/setup.pgsql.sh
Allows to run tests on different ports using the `DB_PORT` environment variable
Had to update InitCommandTest as it parsed the DSN string by value position instead of by key
> allow setting port in tests

- README.md
Updated the "Contribute" segment of the README to feature the link to the test documentation more prominently. Knowing how to run tests locally is very important for new contributors, I think it makes sense to link to the page directly.
There is also a link to a roadmap, but the page has not been updated in 2.5 years. Should we remove that link?
> Update README: add link to test documentation

- src/Propel/Common/Config/Loader/FileLoader.php
- src/Propel/Runtime/Util/PropelDateTime.php
- src/Propel/Runtime/Util/UuidConverter.php
- src/Propel/Runtime/Validator/Constraints/UniqueValidator.php
- tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
PHPStan latest version seems to make master red
This fixes the issues for <=8.1
For 8.2 we first need to add the version into CI matrix and then fix the following:
```
------ -------------------------------------------------------------------------------------------------------------------------- 
Line   Propel/Generator/Behavior/Archivable/ArchivableBehavior.php                                                               
------ -------------------------------------------------------------------------------------------------------------------------- 
69     Call to function property_exists() with Propel\Generator\Model\Table and 'isArchiveTable' will always evaluate to false.  
------ ------------------------------------------------------------------------------------------------------- …
```
> Fix PHPStan

- src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
- src/Propel/Generator/Model/Behavior.php
- src/Propel/Generator/Model/Index.php
- src/Propel/Generator/Model/Table.php
- tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorSyncTest.php
- tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
Allows better management of foreign keys in archivable behavior.
Basically implements #1484 with tests, where FKs can be copied from the source table to an automatically generated archive table.
Also, it adds the possibility to declare new FKs as part of the behavior declaration.
Finally, it adds a parameter `sync`, which, if enabled, copies columns, indexes and optionally fks to an archive table that is not automatically generated, allowing for flexible overriding of archive table properties.
I have added documentation for these options along with the different use cases they cover at propelorm/propelorm.github.com#433
> Manage foreign keys on archivable behavior

- src/Propel/Generator/Command/Executor/RollbackExecutor.php
- src/Propel/Generator/Command/MigrationDownCommand.php
- src/Propel/Generator/Command/MigrationMigrateCommand.php
- src/Propel/Generator/Command/MigrationStatusCommand.php
- src/Propel/Generator/Manager/MigrationManager.php
- tests/Fixtures/migrate-to-version/version-1/schema.xml
- tests/Fixtures/migrate-to-version/version-2/schema.xml
- tests/Fixtures/migrate-to-version/version-3/schema.xml
- tests/Propel/Tests/Generator/Command/MigrationTest.php
- tests/Propel/Tests/Generator/Manager/MigrationManagerTest.php
- Adjusted `MigrationMigrateCommand::execute()` with providing a new option `migrate-to-version` which allows defining the version to migrate database.
- Adjusted `MigrationStatusCommand::execute()` with providing a new option `last-version` which allows receiving the last executed version of the migration.
> Implemented migration rollback.

- src/Propel/Generator/Builder/Util/PropelTemplate.php
- src/Propel/Generator/Reverse/PgsqlSchemaParser.php
- src/Propel/Generator/Reverse/SqliteSchemaParser.php
- src/Propel/Generator/Schema/Dumper/XmlDumper.php
- src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
- src/Propel/Runtime/Adapter/Pdo/OracleAdapter.php
Fix some more PHPStan issues of level 7
~120 issues left
> Fix up PHPStan errors.

- src/Propel/Generator/Platform/DefaultPlatform.php
- src/Propel/Generator/Platform/PlatformInterface.php
- src/Propel/Runtime/Collection/CollectionIterator.php
`ArrayIterator` interface has gone with explicit `true` return values for sort methods.  However, PHP less than 8.2 will crap out on this.  We, instead, add the `#[\ReturnTypeWillChange]` attribute until we can make 8.2 the minimum supported version.
This replaces/closes #1984
> Make compatible with 8.2 ArrayIterator interface updates

- src/Propel/Generator/Platform/Util/AlterTableStatementMerger.php
- src/Propel/Generator/Util/SqlParser.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php
- tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/OraclePlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/PgsqlPlatformMigrationTest.php
- tests/Propel/Tests/Generator/Platform/PlatformMigrationTestProvider.php
Original issue
https://github.com/propelorm/Propel2/pull/1566#issue-643091094
> Added test case

- templates/Builder/Om/baseObjectMethodHook.php
@see https://3v4l.org/dbOp6 when using `is_callable('parent::preSave')`
```
Output for 8.2.0 - 8.2.23, 8.3.0 - 8.3.11
Deprecated: Use of "parent" in callables is deprecated in /in/dbOp6 on line 15
Foo::preSave
Bar::preSave
Output for 5.3.0 - 5.3.29, 5.4.0 - 5.4.45, 5.5.0 - 5.5.38, 5.6.0 - 5.6.40, 7.0.0 - 7.0.33, 7.1.0 - 7.1.33, 7.2.0 - 7.2.34, 7.3.0 - 7.3.33, 7.4.0 - 7.4.33, 8.0.0 - 8.0.30, 8.1.0 - 8.1.29
Foo::preSave
Bar::preSave
```
@see https://3v4l.org/OrSnV when using `is_callable([parent::class, 'preSave'])`, the syntax is also compatible with PHP 7.4, minimal version of the `Propel` library
```
Output for 5.5.0 - 5.5.38, 5.6.0 - 5.6.40, 7.0.0 - 7.0.33, 7.1.0 - 7.1.33, 7.2.0 - 7.2.34, 7.3.0 - 7.3.33, 7.4.0 - 7.4.33, 8.0.0 - 8.0.30, 8.1.0 - 8.1.29, 8.2.0 - 8.2.23, 8.3.0 - 8.3.11 …
```
> Fix php8.2 deprecation - Use of "parent" in callables is deprecated

- src/Propel/Runtime/ActiveQuery/QueryExecutor/AbstractQueryExecutor.php
**Problem statement:**
Originally, propel logs have only an exception, without an explanation of what happened.
And it returns the second part of the exception as a public message.
This fix just log them both together.
> Log the full error message at once

- src/Propel/Runtime/Util/Profiler.php
Using Profiler with custom configuration, like `Propel::getServiceContainer()->setProfilerConfiguration(['slowThreshold' => 0.01]);` it not possible to set float value, when the property itself has `float` type.
> Fixed `Profiler::slowThreshold` setter method to accept float value.

- tests/Propel/Tests/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifierTest.php
- tests/Propel/Tests/Generator/Behavior/Validate/I18nConcreteInheritanceHandleValidateBehaviorTest.php
- tests/Propel/Tests/Generator/Behavior/Validate/ValidateBehaviorTest.php
This fixes deprecation warnings in PHPUnit 9 about `assertClassHasAttribute` being removed in PHPUnit 10.
There is no replacement so PHP's property_exists takes care of it now.
@gechetspr sorry about the PR-spam. Feel free to connect me to anyone else which can look at these PR's. Thank you!
**Edit:** FWIW, `assertObjectHasProperty` was backported tot PHPUnit 9.6.11, but as the name suggests, that works only on objects, not classes.
> phpunit: fix deprecation warnings

- src/Propel/Generator/Behavior/AggregateColumn/AggregateColumnRelationBehavior.php
- src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
- src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
- src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
- src/Propel/Generator/Behavior/Sortable/SortableBehaviorQueryBuilderModifier.php
- src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
- src/Propel/Generator/Builder/Om/ObjectBuilder.php
- src/Propel/Generator/Builder/Om/QueryBuilder.php
- templates/Behavior/Validate/objectValidate.php
> Implicitly marking parameter [...] as nullable is deprecated, the explicit nullable type must be used instead
> PHP 8.4: fix deprecation notice

- src/Propel/Runtime/Util/PropelDateTime.php
- tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
The Problem was the not-type-safe null-check in the PropelDateTime util class.
Passing an Integer 0 (that e.g. comes from the SplFileInfo::getMtime()) to the setter of the field, results in the 0 being interpreted as null, thus the update/insert query is failing.
FIxes #2010
Changelog: Improved falsy value handling in PropelDateTime; now treats '', false, and null as null, and '0' as the Unix epoch
> FIX failing queries on datetime fields set to 1970-01-01 00:00:00 via (int) 0

- src/Propel/Runtime/Connection/PdoConnection.php
forward $name to underlying PDO when calling lastInsertId
> Fix lastInsertId to forward sequence name

- src/Propel/Runtime/Collection/CollectionIterator.php
- tests/Propel/Tests/Runtime/Collection/CollectionIteratorTest.php
- fix CollectionIterator::asort() and ksort() to use flags
- test that sorting respects flags
> Fix sorting flags in CollectionIterator
