src/Propel/Runtime/Parser/JsonParser.php, tests/Propel/Tests/Runtime/Parser/JsonParserTest.php
=> Convert DateTime to ISO8601-String in JsonParser before calling json_encode

src/Propel/Generator/Reverse/PgsqlSchemaParser.php
My second try to fix issue #840.
=> Fix #840 Migration of unique/index keys in PgSQL

src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php, src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php, src/Propel/Generator/Behavior/NestedSet/templates/objectGetIterator.php, src/Propel/Generator/Behavior/NestedSet/templates/objectInsertAsLastChildOf.php, tests/Propel/Tests/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifierTest.php
* type hints
* better doc comments
* code format
* using `->exists()` instead of `->count() > 0`
* `getFirstChild` and `getLastChild`: Returning `null` instead of `array()` for leaves
=> NestedSetBehavior improvements

src/Propel/Generator/Builder/Om/ObjectBuilder.php, src/Propel/Runtime/Parser/JsonParser.php, tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectTest.php, tests/Propel/Tests/Runtime/Parser/JsonParserTest.php
=> Changed toArray to format temporal columns as ISO8601 strings

src/Propel/Generator/Builder/Om/ObjectBuilder.php, tests/Propel/Tests/Runtime/TypeTest.php
Compare serialized object against stream content, instead of the stream handle
=> Fixed setter for objects columns

src/Propel/Runtime/ActiveQuery/Join.php, src/Propel/Runtime/ActiveQuery/ModelJoin.php, src/Propel/Runtime/Formatter/ArrayFormatter.php, src/Propel/Runtime/Formatter/ObjectFormatter.php, src/Propel/Runtime/Formatter/SimpleArrayFormatter.php, tests/Propel/Tests/BookstoreLoggingTest.php, tests/Propel/Tests/Runtime/Formatter/ObjectFormatterWithTest.php, tests/bin/setup.mysql.sh
- Fixed setup.mysql.sh to use DB_PW EV Param
- Added some more LogicExceptions on with-usage and limit
=> Added polimorphic joining ability from one to many

src/Propel/Runtime/ActiveQuery/ModelCriteria.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaSelectTest.php, tests/Propel/Tests/Runtime/ActiveQuery/SubQueryTest.php
This PR fixes an issue with select columns in addition to `withColumn` usages.
=> Fix usage of addSelfSelectColumns in context of withColumn usages

src/Propel/Runtime/ActiveQuery/Criteria.php, tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
This fixes propelorm/Propel2#865.
=> Fix #865: set limit to -1 in clear method

src/Propel/Generator/Model/Table.php, src/Propel/Generator/Reverse/SqliteSchemaParser.php, tests/Fixtures/bookstore/schema.xml, tests/Fixtures/schemas/schema.xml, tests/Propel/Tests/Generator/Builder/Om/AbstractOMBuilderRelatedByTest.php, tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php, tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php, tests/Propel/Tests/Generator/Model/ModelTestCase.php, tests/Propel/Tests/Generator/Model/TableTest.php, tests/Propel/Tests/Runtime/Formatter/ArrayFormatterWithTest.php, tests/Propel/Tests/Runtime/Formatter/ObjectFormatterWithTest.php, tests/Propel/Tests/Runtime/Formatter/OnDemandFormatterWithTest.php, tests/Propel/Tests/Runtime/Map/RelatedMapSymmetricalTest.php, tests/Propel/Tests/Runtime/Map/RelatedMapSymmetricalWithSchemasTest.php
Was a hell of work fixing all the tests -.-
=> Fixed #711 by throwing an excetion if one try to add a foreign key twice

src/Propel/Generator/Platform/MysqlPlatform.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaSelectTest.php
Hello,
This is just a tiny pull request to fix a few typos and remove a useless comment.
Have a nice day.
=> Fix a few typos [ci skip]

tests/Propel/Tests/Runtime/Collection/ObjectCollectionTest.php
Additional test to cover: https://github.com/propelorm/Propel2/blob/master/src/Propel/Runtime/Collection/ObjectCollection.php#L270-272
=> Improve ObjectCollection coverage

src/Propel/Generator/Platform/DefaultPlatform.php, src/Propel/Generator/Reverse/MysqlSchemaParser.php, tests/Propel/Tests/Generator/Platform/MysqlPlatformTest.php
=> Fix default type size with scale

src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php, src/Propel/Generator/Behavior/Delegate/templates/queryMethodsTemplate.php
Implemented filtering and orderBy*() by delegated table properties. Also, toArray() now returns delegated properties too.
=> Some improvements of DelegateBehavior

src/Propel/Generator/Schema/Dumper/XmlDumper.php, tests/Propel/Tests/Resources/blog-database.php, tests/Propel/Tests/Resources/blog-database.xml, tests/Propel/Tests/Resources/blog-schema.xml
=> Fix reverse command on decimal field with 0 as scale

src/Propel/Common/Config/PropelConfiguration.php, src/Propel/Generator/Command/MigrationDiffCommand.php, src/Propel/Generator/Manager/ReverseManager.php, src/Propel/Generator/Model/Database.php, src/Propel/Generator/Model/Diff/DatabaseComparator.php
Implemented handled of new schema.xml attribute «external» which force to skip marked table on `migration:diff` action.
=> External attribute added

src/Propel/Generator/Builder/Om/QueryBuilder.php
=> Add JoinWith phpdoc

src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php, src/Propel/Generator/Model/Table.php
DelegateBehavior : generated code was invalid if schema prefix
=> Fix schema in DelegateBehavior

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Add more phpdoc, useful for documentation generators.
=> Add description to column attribute's comment

resources/dtd/database.dtd
See "Global Vendor Info" http://propelorm.org/documentation/reference/schema.html
=> vendor element missing from DTD

src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php, tests/Propel/Tests/Issues/Issue1033Book.php, tests/Propel/Tests/Issues/Issue1033Test.php
See #1033 for additional information.
=> Fix #1033 prevent static properties from serializing

src/Propel/Runtime/ActiveQuery/ModelCriteria.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
Does anyone have a better idea how to solve it? I didn't find a way to get `TableMap` by table name.
Fixes #1037
=> allow select column from joined table

src/Propel/Generator/Util/QuickBuilder.php
Fixes warnings introduced by [the fix](https://github.com/propelorm/Propel2/pull/1056) to issue https://github.com/propelorm/Propel2/issues/1052
=> Fix warnings in issue 1052

src/Propel/Generator/Platform/PgsqlPlatform.php, tests/Propel/Tests/Generator/Platform/PgsqlPlatformMigrationTest.php, tests/Propel/Tests/Generator/Platform/PgsqlPlatformTest.php
Single platform solution for #1048
=> Implemented migration transactions for PostgreSQL

src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
=> dropped 2nd arg passed to findMethod. The method only has one arg.

src/Propel/Runtime/Collection/ObjectCollection.php, tests/Propel/Tests/Runtime/Collection/ObjectCollectionWithFixturesTest.php
From the issue https://github.com/propelorm/Propel2/issues/1023
=> Implemented method getColumnValues for export of column values.

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Base classes in a different namespace are currently not supported. It would be great, if you would consider this change, that this becomes a part of the standard functionality.
Thanks, Andreas
=> Implemented use statement for baseClass

tests/Propel/Tests/Generator/Reverse/PgsqlSchemaParserTest.php
Please see #1087 for detail information. Thanks
=> [PgsqlSchemaParserTest] set database schema to 'public'

src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php
Archive behavior was not acknowledging the identifierQuoting parameter on the parent table.
=> Add identifierQuoting to archive behavior tables

src/Propel/Generator/Behavior/Sluggable/SluggableBehavior.php, tests/Propel/Tests/Resources/blog-database.xml, tests/Propel/Tests/Resources/blog-schema.xml
Added the ability to configure whether or not to use a unique constraint on the slug_column of the table for the SluggableBehavior.
+ some additional docblock fixes
=> Added: config unique constraint of slug_column

src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php, src/Propel/Generator/Builder/Om/ObjectBuilder.php, src/Propel/Runtime/Collection/ObjectCollection.php, src/Propel/Runtime/Formatter/AbstractFormatter.php, src/Propel/Runtime/Formatter/ObjectFormatter.php, src/Propel/Runtime/Map/TableMap.php, tests/Propel/Tests/Runtime/Map/TableMapTest.php
I found a bug with Custom collections http://sandbox.propelorm.org/5ca766e and fixed it.
Now we don't get exception, and get correct collection all time.
=> Fixed custom collections

src/Propel/Generator/Util/PhpParser.php
This speeds up generation process of large schemas considerably (~25%). refs #1066.
perf profiles (this numbers are not 100% accurate since more changes are included then this PR. See accurate numbers in https://github.com/propelorm/Propel2/pull/1067#issuecomment-163859751)
- before patch: https://blackfire.io/profiles/dd03dc97-cdc6-4f6f-bbcf-899cdc5b6918/graph (2 minutes and 13 seconds)
- after patch: https://blackfire.io/profiles/35114fdc-8aec-4ea2-ba31-e88d8bec865e/graph (1 minute and 40 seconds)
=> Cache method information in PhpParser.

.travis.yml
=> removed php5.4 from travis build.

src/Propel/Generator/Command/ModelBuildCommand.php
Typo-ed option name when reading the option.
=> Fix --object-class option not being considered when building model

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Fixes issue with multiple FKs referencing the same table despite different PhpNames specified.
=> Fixes issue #892 with multiple FKs to the same table

src/Propel/Generator/Command/templates/propel.json.php, src/Propel/Generator/Command/templates/propel.php.php
=> Fixed password not set in php config by `propel init`

src/Propel/Generator/Builder/Om/QueryBuilder.php, tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php
=> findPk should not use instance pool for non empty queries

tests/Propel/Tests/Common/Config/ConfigurationManagerTest.php, tests/Propel/Tests/Generator/Config/GeneratorConfigTest.php, tests/Propel/Tests/Generator/Config/QuickGeneratorConfigTest.php
Fix unit tests that were broken by: https://github.com/propelorm/Propel2/pull/1125
=> Fix model_paths unit tests

src/Propel/Common/Config/PropelConfiguration.php
config attributes should support ATTR_TIMEOUT for configure PDO timeout
=> PDO connect timeout

.travis.yml
Removing some defaults.. Try to make the travis composer cache work and no longer trigger api limits
=> Speedup travis builds

src/Propel/Generator/Behavior/QueryCache/QueryCacheBehavior.php, tests/Propel/Tests/Generator/Behavior/QueryCache/QueryCacheTest.php
=> Fix issue #1162

src/Propel/Generator/Reverse/MysqlSchemaParser.php
Add the missing native type **`SET`** when parsing columns with MySQL
=> Add "set" type when parsing MySQL columns

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Small adjust in PHPDoc 'class opening' of the generated model
=> Fix PHPDoc on open class

resources/dtd/database.dtd, resources/xsd/database.xsd
Polymorphic relations are supported a long time now (https://github.com/propelorm/Propel2/pull/864) but DTD/XSD aren't aware of that
=> Polymorphic relations allowed by DTD/XSD

resources/xsd/database.xsd
quick fix for #1207, sorry, my mistake :(
=> value part of reference should be optional

src/Propel/Generator/Reverse/PgsqlSchemaParser.php
Not 100% sure about the character varying mapping to varchar although it seems appropriate.
=> Added some missing types for PGSQL

src/Propel/Runtime/Validator/Constraints/UniqueValidator.php, tests/Propel/Tests/Generator/Behavior/Validate/UniqueConstraintTest.php
Test for @fenric solution.
Solving the #943 issue.
=> Unique validator fix.

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Fixing a bug where this referenced criteria->insert which is not defined.
=> Set $criteria->insert to $criteria->doInsert

src/Propel/Generator/Command/InitCommand.php
Runs the next commands required to be able to use Propel
=> Run sql:build model:build config:convert post-init

src/Propel/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifier.php, tests/Propel/Tests/Generator/Behavior/Versionable/VersionableBehaviorObjectBuilderModifierTest.php
Fix behavior when versionable column is pk, documented methods and implementing tests. Fixing issue #1109
=> Fix versionable behavior when exists 1:1 relationships

src/Propel/Runtime/Util/PropelDateTime.php, tests/Propel/Tests/Runtime/Util/PropelDateTimeTest.php
=> Added test for timezone in PropelDateTime::createHighPrecision

src/Propel/Runtime/Connection/PdoConnection.php
Compatibility of numeric and string keys
=> Compatibility of numeric and string keys

src/Propel/Generator/Builder/Om/ObjectBuilder.php
Generated code looks like
```
if ($this->getLyrics()->contains($lyric)) { $artistLyric = new ArtistLyric();
$artistLyric->setLyric($lyric);
```
Fix to
```
if ($this->getLyrics()->contains($lyric)) {
$artistLyric = new ArtistLyric();
$artistLyric->setLyric($lyric);
```
=> Code format fix for generated code for remove***

src/Propel/Generator/Behavior/Delegate/templates/queryMethodsTemplate.php
=> Changes description of filterBy function

composer.json, tests/Propel/Tests/Generator/Behavior/Validate/I18nConcreteInheritanceHandleValidateBehaviorTest.php
This fix https://github.com/propelorm/Propel2/issues/1347
=> Validator fix

src/Propel/Generator/Behavior/I18n/I18nBehaviorObjectBuilderModifier.php
=> Undefined method being called; issue #1352

src/Propel/Generator/Builder/Om/ObjectBuilder.php
=> fix ObjectBuilder addFKAccessor reference to int

README.md
URL inside quotes should be encoded.
=> Fix Gitter

src/Propel/Runtime/Formatter/ObjectFormatter.php
serialize primary key only once
=> improved formatting speed

src/Propel/Runtime/ActiveQuery/InstancePoolTrait.php
address countable issue in php7.2 and update if/else structure for unnecessary else
fixes #1424
**NOTE:** _I am not new to using propel but new to the internals of her; it will need someone with some local knowledge_
=> address countable issue in php7.2

.travis.yml, src/Propel/Generator/Command/InitCommand.php, src/Propel/Runtime/ActiveQuery/InstancePoolTrait.php, src/Propel/Runtime/ActiveQuery/ModelCriteria.php, tests/Propel/Tests/Generator/Command/InitCommandTest.php, tests/Propel/Tests/Issues/Issue730Test.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaSelectTest.php
=> Fix test suite and init command

composer.json
Add symfony 5 compatibility and Laravel 7.x compatibility.
=> Add symfony 5 compatibility

composer.json, src/Propel/Common/Config/PropelConfiguration.php, src/Propel/Generator/Behavior/AggregateColumn/AggregateColumnBehavior.php, src/Propel/Generator/Manager/ReverseManager.php, src/Propel/Generator/Model/Column.php, src/Propel/Generator/Model/Diff/TableComparator.php, src/Propel/Generator/Model/PropelTypes.php, src/Propel/Generator/Platform/OraclePlatform.php, src/Propel/Runtime/ActiveQuery/Criterion/BasicCriterion.php, src/Propel/Runtime/ActiveQuery/Criterion/BinaryCriterion.php, src/Propel/Runtime/ActiveQuery/Criterion/InCriterion.php, src/Propel/Runtime/ActiveQuery/Criterion/LikeCriterion.php, src/Propel/Runtime/Adapter/MSSQL/MssqlPropelPDO.php, src/Propel/Runtime/Collection/Collection.php, src/Propel/Runtime/Parser/XmlParser.php, tests/phpstan.neon
long term we should reach at least level 5, and BC check using prefer lowest
//cc @stereomon 
For now this is WIP
as we cannot merge in a php7+ only tool just yet.
So for now it just finds/reports in this branch 270+ errors to be fixed on that first level 1.
On level 5 there are 1283+ errors.
Important bugs (see fixme) and issues can be cherry picked into current master.
=> Add phpstan on lowest level 1 for now.

.travis.yml
Addresses https://github.com/propelorm/Propel2/issues/1569
=> Make travis run postgresql 12

.travis.yml, composer.json, src/Propel/Generator/Behavior/Validate/ValidateBehavior.php, src/Propel/Runtime/Validator/Constraints/Date.php, src/Propel/Runtime/Validator/Constraints/DateValidator.php
Propel passes when using symfony validator v5.
=> Sf validator v5

composer.json, resources/xsd/database.xsd, src/Propel/Generator/Builder/Om/AbstractObjectBuilder.php, src/Propel/Generator/Builder/Om/ExtensionObjectBuilder.php, src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php, src/Propel/Generator/Builder/Om/ExtensionQueryInheritanceBuilder.php, src/Propel/Generator/Builder/Om/InterfaceBuilder.php, src/Propel/Generator/Builder/Om/MultiExtendObjectBuilder.php, src/Propel/Generator/Builder/Om/ObjectBuilder.php, src/Propel/Generator/Builder/Om/QueryBuilder.php, src/Propel/Generator/Builder/Om/QueryInheritanceBuilder.php, src/Propel/Generator/Builder/Om/TableMapBuilder.php, tests/Propel/Tests/Helpers/Bookstore/BookstoreTestBase.php, tests/Propel/Tests/Runtime/Map/GeneratedRelationMapTest.php, tests/Propel/Tests/Runtime/Map/GeneratedRelationMapWithSchemasTest.php
We forgot to properly include
https://github.com/propelorm/Propel2/compare/stable-2.0.0
The branch never really made sens to begin with, and we should port all missing pieces and close it
Ther versioning part is here now.
=> Cleanup PHP versioning mentioned.

src/Propel/Generator/Builder/Om/AbstractOMBuilder.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaWithNamespaceTest.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaWithSchemaTest.php
Fixes https://github.com/propelorm/Propel2/issues/1619
=> Remove default value of optional parameters followed by required parameters

src/Propel/Generator/Reverse/PgsqlSchemaParser.php
=> add json to native pgsql type

src/Propel/Generator/Manager/ReverseManager.php
Resolves https://github.com/propelorm/Propel2/issues/1649
=> Fix table name logging for ReverseManager

src/Propel/Generator/Model/ForeignKey.php, src/Propel/Generator/Model/Table.php, tests/Propel/Tests/Generator/Builder/Om/QueryBuilderTest.php, tests/Propel/Tests/Generator/Model/ForeignKeyTest.php, tests/Propel/Tests/Issues/Issue1659Test.php
=> #1659 skip incomplete check for non-primary foreign key

.github/workflows/ci.yml, .travis.yml, README.md
Moved CodeStyle and static checks to github actions.
https://github.com/propelorm/Propel2/issues/1668
=> Move static check to GitHub actions

.github/workflows/ci.yml, README.md
-  Create and upload code coverage report for all dbms, to include all vendor specific tests, too.
-  Remove Code Climate coverage from `README.md`
=> Upload code coverage report for all dbms

tests/Propel/Tests/Generator/Model/DatabaseTest.php, tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationMyISAMTest.php, tests/Propel/Tests/Generator/Platform/MysqlPlatformMigrationTest.php, tests/Propel/Tests/Runtime/Parser/AbstractParserTest.php, tests/Propel/Tests/Runtime/Parser/fixtures/test_data.xml
Move some other tests from physical to virtual filesystem.
=> Continue mocking filesystem

phpstan.neon, psalm-baseline.xml, src/Propel/Generator/Behavior/AggregateMultipleColumns/AggregateMultipleColumnsBehavior.php, src/Propel/Generator/Behavior/AggregateMultipleColumns/templates/objectCompute.php, src/Propel/Generator/Behavior/AggregateMultipleColumns/templates/objectUpdate.php, src/Propel/Generator/Builder/Util/SchemaReader.php, tests/Fixtures/bookstore/behavior-aggregate-multiple-schema.xml, tests/Propel/Tests/Generator/Behavior/AggregateMultipleColumns/AggregateMultipleColumnsBehaviorTest.php, tests/Propel/Tests/Generator/Builder/Util/SchemaReaderTest.php, tests/Propel/Tests/Generator/Model/BehaviorTest.php
In a project, I have to propagate several aggregated columns across several tables using the AggregateColumn behavior. It is similar to having items, which are aggregated on their groups, which are aggregated on their owner. This works fine, except I noticed that the AggregateColumn behavior causes extensive update cascades when changing the aggregation source table. In my project, there are four aggregation columns on three tables, and a single insert, update or delete on the source table causes a whooping  32 subsequent updates. This has become a problem, particularly when deleting several items takes about a minute, when it should be a fraction of a second.
Reason for the update cascade is that AggregateColumn behavior triggers a save for each aggregation, which in turn triggers the …
=> Aggregate multiple columns behavior & parameter list support

src/Propel/Generator/Builder/Om/templates/baseObjectMethodMagicCall.php, src/Propel/Generator/Builder/Om/templates/baseObjectMethods.php, src/Propel/Runtime/Collection/Collection.php, src/Propel/Runtime/Collection/OnDemandCollection.php, tests/Propel/Tests/Runtime/ActiveRecordConvertTest.php
Had this laying around: Bugfixes for #1672
=> Fixes for #1672 - fromArray with keyType

src/Propel/Generator/Manager/AbstractManager.php, tests/Propel/Tests/Generator/Manager/AbstractManagerTest.php
Had this laying around: Test case for #1491 and some fixes
=> Test and fixes for #1491 - resolve external schema location relative to file

src/Propel/Generator/Builder/Om/TableMapBuilder.php, tests/Propel/Tests/Generator/Builder/Om/TableMapBuilderTest.php
The generated code duplicates keys in the normalized column name map array in certain cases where two variants of how to specify a column accidentally create the exact same spelling.
For example the spelling of a single word column name is the same when using camelcase or snake_case. PHP ignorhes this but many tools flag this as a potential error, hence this fix.
Marked draft as I have to figure out the unit tests
=> fixes duplicate keys in normalizedColumnNameMap

tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
https://github.com/propelorm/Propel2/pull/1765
=> Fixed test for php8.1

tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
-Adjusted `ModelCriteriaTest::testHavingWithColumn()` so all checks have passed
Refs https://github.com/propelorm/Propel2/pull/1765
=> Fixed test php8.1

src/Propel/Generator/Behavior/QueryCache/QueryCacheBehavior.php, src/Propel/Generator/Builder/Om/QueryBuilder.php, src/Propel/Runtime/ActiveQuery/ModelCriteria.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaGroupByArrayTest.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaSelectTest.php, tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php, tests/Propel/Tests/Runtime/ActiveQuery/SubQueryTest.php
Undoes most of the changes from https://github.com/propelorm/Propel2/pull/1711
as requested in https://github.com/propelorm/Propel2/issues/1733#issuecomment-907154887
=> Reintroduce late select for backward compatibility

src/Propel/Runtime/Parser/XmlParser.php, tests/Propel/Tests/Runtime/Parser/XmlParserTest.php
Resolves https://github.com/propelorm/Propel2/issues/1808
=> Remove deprecated ATOM datetime format.

src/Propel/Generator/Platform/DefaultPlatform.php
Resolves https://github.com/propelorm/Propel2/issues/1796
=> Format insert TIME values as H:i:s.u instead of 'Y-m-d H:i:s.u'

tests/Propel/Tests/Generator/Platform/DefaultPlatformTest.php
Tests for https://github.com/propelorm/Propel2/pull/1797
=> Add tests for $stmt->bindValue()

.github/workflows/ci.yml, src/Propel/Generator/Command/AbstractCommand.php, src/Propel/Generator/Reverse/MysqlSchemaParser.php, src/Propel/Runtime/Parser/CsvParser.php
=> Use explode() instead of preg_split().

src/Propel/Generator/Builder/DataModelBuilder.php, src/Propel/Generator/Builder/Om/AbstractOMBuilder.php, src/Propel/Generator/Builder/Om/ObjectBuilder.php, src/Propel/Runtime/ActiveQuery/Criteria.php, src/Propel/Runtime/ActiveQuery/ModelCriteria.php, src/Propel/Runtime/Collection/ObjectCollection.php
=> https://github.com/propelorm/Propel2/pull/1833
=> Adjust as per review.

src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php, src/Propel/Generator/Manager/AbstractManager.php, src/Propel/Generator/Model/Table.php
- Fix prop name
- Undeprecate XSD (only XSL is defunct)
- Remove long dead part
=> Cleanup on deprecated API

phpstan-baseline.neon, src/Propel/Runtime/Formatter/AbstractFormatter.php
Since we are not solving it, this at least fixes the silencing issue and documents the truth about the abstract one
https://github.com/propelorm/Propel2/issues/1622
=> Fix up phpstan silencing.

phpstan-baseline.neon, src/Propel/Generator/Builder/DataModelBuilder.php, src/Propel/Generator/Config/GeneratorConfig.php, src/Propel/Generator/Model/Database.php, src/Propel/Generator/Model/ForeignKey.php, src/Propel/Generator/Platform/MysqlPlatform.php, src/Propel/Generator/Platform/PgsqlPlatform.php, src/Propel/Runtime/Adapter/Pdo/MssqlAdapter.php
Afterwards we should
vendor/bin/phpstan -b
=> Fix up phpstan baseline.

src/Propel/Common/Util/PathTrait.php
Follow https://github.com/propelorm/Propel2/pull/1848
Just to make sure we ease the upgrade issues here for folks that use behaviors or other custom repositories with extension and templates.
=> Add BC shim for template lookup in former directories.

phpstan-baseline.neon, phpstan.neon, psalm-baseline.xml, src/Propel/Runtime/ActiveQuery/ModelCriteria.php
=> Fix up CI - PHPStan, CS, Psalm

.github/workflows/ci.yml, composer.json
For some reason Psalm isn't running the same for CI as local.  It's also running again the `vendor` dir on CI, which is wrong.  Additionally, I get a lot of analysis errors locally when targeting the default config.  It's possible the CI isn't properly using it either.
=> Fixing Psalm CI Issues

src/Propel/Common/Config/ConfigurationManager.php, src/Propel/Common/Pluralizer/StandardEnglishPluralizer.php, src/Propel/Common/Util/SetColumnConverter.php, src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php, src/Propel/Generator/Behavior/I18n/I18nBehavior.php, src/Propel/Generator/Behavior/Sortable/SortableBehavior.php, src/Propel/Generator/Behavior/Versionable/VersionableBehavior.php, src/Propel/Generator/Builder/DataModelBuilder.php, src/Propel/Generator/Manager/AbstractManager.php, src/Propel/Generator/Manager/MigrationManager.php, src/Propel/Generator/Model/CrossForeignKeys.php, src/Propel/Generator/Model/Diff/DatabaseDiff.php, src/Propel/Generator/Reverse/AbstractSchemaParser.php, src/Propel/Runtime/ActiveQuery/Criterion/AbstractCriterion.php, src/Propel/Runtime/ActiveQuery/Join.php, src/Propel/Runtime/ActiveQuery/Lock.php, src/Propel/Runtime/ActiveQuery/ModelCriteria.php, src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php, src/Propel/Runtime/Collection/ObjectCollection.php, src/Propel/Runtime/Connection/StatementWrapper.php, src/Propel/Runtime/ServiceContainer/StandardServiceContainer.php, src/Propel/Runtime/Util/PropelModelPager.php, tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectLobTest.php
=> Docblock cleanup

src/Propel/Generator/Behavior/Archivable/ArchivableBehavior.php, tests/Propel/Tests/Generator/Behavior/Archivable/ArchivableBehaviorTest.php
=> Fix duplicate indices when converting unique index to index

phpcs.xml, src/Propel/Common/Config/Loader/FileLoader.php, src/Propel/Generator/Manager/AbstractManager.php, src/Propel/Generator/Util/VfsTrait.php, src/Propel/Runtime/ActiveQuery/Criteria.php, src/Propel/Runtime/Adapter/Pdo/MysqlAdapter.php, src/Propel/Runtime/Adapter/Pdo/OracleAdapter.php, src/Propel/Runtime/Adapter/Pdo/PgsqlAdapter.php
For https://github.com/propelorm/Propel2/issues/1921
=> Fix CS by removing Yoda silencing.

phpcs.xml, src/Propel/Generator/Command/InitCommand.php, src/Propel/Runtime/Map/DatabaseMap.php
=> Fixed CS and removed silencing in config.

.github/workflows/ci.yml
@gechetspr this fixes the deprecation warnings in GitHub actions.
=> ci: fix deprecation messages

.github/workflows/ci.yml, tests/Fixtures/bookstore/schema.xml
- GA Action fails with new GH API
- Fix an issue with the test in bookstore unit tests.
=> Use updated calls of GH actions api
